## Applying Feature Engineering on our dataset

In [185]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [186]:
p_dir = project_dir()
clean_data_dir = p_dir.CLEANED_DIR

category_name = clean_data_dir/'category_name.csv'
customers = clean_data_dir/'clean_customers.csv'
location = clean_data_dir/'cleaned_location.csv'
order_payments = clean_data_dir/'cleaned_order_payments.csv'
orders_items = clean_data_dir/'cleaned_orders_items.csv'
order_reviews = clean_data_dir/'cleaned_order_reviews.csv'
orders = clean_data_dir/'cleaned_orders.csv'
products = clean_data_dir/'cleaned_products.csv'
sellers = clean_data_dir/'cleaned_sellers.csv'

In [187]:
orders_df = pd.read_csv(orders)
orders_df = orders_df.drop('Unnamed: 0',axis=1)
orders_df.sample(5)

payments_df = pd.read_csv(order_payments)
payments_df = payments_df.drop('Unnamed: 0',axis=1)
payments_df.sample(5)

orders_items_df = pd.read_csv(orders_items)
orders_items_df = orders_items_df.drop('Unnamed: 0',axis=1)
orders_items_df.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
81972,ba4f4ffc1063e52435824b76fc7933a6,1,191bd142a00d0d95fa54118635886d9e,7142540dd4c91e2237acb7e911c4eba2,2017-09-29 13:25:49,84.9,17.84
77922,b1526a2bd67c99a417bbd10df7904bb0,1,389d119b48cf3043d311335e499d9c6b,1f50f920176fa81dab994f9023523100,2018-03-22 19:47:37,53.9,52.95
55803,7edf24d26573e36b72c670b3810ab3e0,1,b1d207586fca400a2370d50a9ba1da98,1ca7077d890b907f89be8c954a02686a,2018-01-26 18:17:00,149.0,8.30
70371,a0965651e1058585af3d91274b10886e,1,f1c7f353075ce59d8a6f3cf58f419c9c,37be5a7c751166fbc5f8ccba4119e043,2017-07-13 17:15:28,205.0,22.27
39143,58ee11026c2fdda6ff738c392cc5fb00,1,ba85af910c6f4624929eaf3879d72321,59b22a78efb79a4797979612b885db36,2017-08-09 03:04:56,59.0,15.16

In [188]:
orders_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [189]:
## Creating a new columns of total amount of by doing sum of price and fright value
orders_items_df['total_amount'] = orders_items_df['price'] + orders_items_df['freight_value']

In [190]:
orders_items_df.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount
63892,91eef134a9dc65e566fde368f1772b93,1,727a46f0b58a9ef165af9f7ebcfebfa9,e9779976487b77c6d4ac45f75ec7afe9,2018-06-10 22:50:31,19.49,7.87,27.36
70523,a0f3677ac2cfd35a8d76f4a26fb29a95,1,e0d64dcfaa3b6db5c54ca298ae101d05,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-23 01:17:35,127.00,17.80,144.80
13541,1ecad0e8ea57760ebd5ea7863ec48b06,2,6e1b14d3cbb5fb3a2c00351007127dfd,7a67c85e85bb2ce8582c35f2203ad736,2017-08-04 07:15:12,229.99,17.24,247.23
6798,0f6665a373c36216e96163b3162404b0,1,c01cc7b6054e22d68972a35df1e0c249,a67780aba9dd436e7ac0aa1f889e73ec,2018-02-06 13:52:03,42.60,31.10,73.70
86901,c5585ae33ee215aeee0d7f9aaec67cde,2,9cb2ed2f273027b8daa3b0863368105c,76d5af76d0271110f9af36c92573f765,2017-12-05 02:20:00,39.90,16.11,56.01

In [191]:
orders_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_estimated_deliverey_date'],
      dtype='str')

In [192]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   order_id                        99441 non-null  str
 1   customer_id                     99441 non-null  str
 2   order_status                    99441 non-null  str
 3   order_purchase_timestamp        99441 non-null  str
 4   order_approved_at               99281 non-null  str
 5   order_delivered_carrier_date    97658 non-null  str
 6   order_delivered_customer_date   96476 non-null  str
 7   order_estimated_delivery_date   99441 non-null  str
 8   order_estimated_deliverey_date  99441 non-null  str
dtypes: str(9)
memory usage: 6.8 MB

In [193]:
# fixing the dtype
date_col = [
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_col:
    orders_df[col] = pd.to_datetime(orders_df[col])

In [194]:
orders_df = orders_df.drop('order_estimated_deliverey_date',axis=1)

In [195]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](4), str(4)
memory usage: 6.1 MB

In [196]:

# creating a new columns in orders_df delivery_days usig order_purchase_timestamp and order_delivered-customer_date
orders_df = orders_df.rename(
    columns={
        'order_purchase_timestamp' : 'order_purchase',
        'order_approved_at' : 'approved_at',
        'order_delivered_carrier_date' : 'delivered_carrier_date',
        'order_delivered_customer_date' : 'delivered_customer_date',
        'order_estimated_delivery_date' : 'estimated_delivery_date'
    }
)



orders_df['delivery_days'] = (orders_df['delivered_customer_date'] - orders_df['approved_at']).dt.days
# orders_df.sample(5)

In [197]:
# adding a new columns delivery_delay

orders_df ['delivery_delay_days'] = (orders_df['delivered_customer_date'] - orders_df['estimated_delivery_date']).dt.days

# orders_df = orders_df.drop('delivery_delay',axis=1)

# adding a new columns is_delayed 
orders_df['is_delayed'] = (orders_df['estimated_delivery_date'] < orders_df['delivered_customer_date']).astype(int)

In [198]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed
4272,e22a3e8048469ea68906f666d446c25c,aa0533eb31ed3be79086f11bb2bec430,delivered,2017-08-28 09:48:01,2017-08-28 10:05:04,2017-08-29 11:05:28,2017-09-05 21:42:35,2017-09-19,8.0,-14.0,0
86970,67c8fda9d347535e923f93614f2b44e0,ec0c08af5c172f4e494932f5c75e4458,delivered,2017-11-25 02:11:32,2017-11-28 03:18:25,2017-11-28 19:29:05,2017-12-13 21:36:43,2017-12-15,15.0,-2.0,0
80399,72957a7ebd28baf4446a71d68ff98de5,a1b041bf294ac9a4c79a3ade1f9c5bac,delivered,2018-07-08 13:06:41,2018-07-08 13:25:26,2018-07-11 13:36:00,2018-07-12 23:18:30,2018-07-19,4.0,-7.0,0
34799,9eead354475b8b8fde3811f26b2599fc,13e7480f7e6534616eca292f8267ef56,delivered,2017-11-28 13:30:58,2017-11-28 13:51:05,2017-11-29 16:02:43,2017-12-06 14:28:59,2017-12-27,8.0,-21.0,0
72304,c811b2b32820eb21f261701e61e863c5,310f4c1ebfa70d27337359ee72d472b0,delivered,2018-04-05 10:29:03,2018-04-06 03:28:23,2018-04-07 01:32:59,2018-04-10 16:37:51,2018-04-27,4.0,-17.0,0

In [199]:
customers_df = pd.read_csv(customers,index_col=0)
customers_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [200]:
# merging customers and orders tables
orders_df = orders_df.merge(
    customers_df[['customer_id','customer_unique_id']],
    on='customer_id',
    how='left'
)

orders_df.duplicated().sum()

np.int64(0)

In [201]:
orders_df['customer_order_count'] =orders_df.groupby('customer_unique_id')['order_id'].transform('count')

In [202]:
orders_df['customer_order_count'].value_counts()

# adding bool columns bout is it a repeat customer
orders_df['is_repeat_customer'] = (orders_df['customer_order_count'] > 1).astype(int)

In [203]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer
64342,352d885bc141f75e361bbf6501513d25,8f458f1a3f921406c1dda20db858fb40,delivered,2018-03-20 12:22:25,2018-03-20 12:35:22,2018-03-27 00:12:21,2018-03-31 19:53:42,2018-04-02,11.0,-2.0,0,9e45e105f9d3bbd65e327127e0a71a55,1,0
19739,f6bfc9902c58791929c6ba9af3953696,e6305a0a9355e91aad86e234263a41aa,delivered,2017-05-07 13:46:44,2017-05-07 14:02:15,2017-05-08 11:45:00,2017-05-17 11:12:37,2017-05-31,9.0,-14.0,0,ff4b2772a9368e8b30a1ebd484de12c9,1,0
94331,6e7e891760708803a2f4203981f2d69d,9bc1b48bb57b22ba2fbd77579dad8202,unavailable,2017-02-16 19:43:11,2017-02-16 19:55:17,NaT,NaT,2017-03-17,NaN,NaN,0,b3c3ded83fde176416890b31406e2415,1,0
31071,8c33d668c93faeb68c9fbf5fadd93e3a,f65a9d5dc0c49064efc04ca1d4667935,delivered,2017-04-23 11:33:03,2017-04-23 11:42:10,2017-04-25 08:47:25,2017-05-11 12:29:50,2017-05-30,18.0,-19.0,0,5d622f341bd6b5e3d07c22484f869f4f,1,0
92772,95617572e4e39b8b9f5384d136111f93,1801ef99dbe925417e3103f8adafb25a,delivered,2018-02-03 09:59:51,2018-02-03 10:33:40,2018-02-05 23:33:53,2018-02-20 16:07:14,2018-03-08,17.0,-16.0,0,7d03dbebae935f56b7df8bb280aaaa15,1,0

In [204]:
# total spending per customer

orders_df.groupby('customer_unique_id')['order_id'].transform('count')

0        2
1        1
2        1
3        1
4        1
        ..
99436    1
99437    1
99438    1
99439    1
99440    1
Name: order_id, Length: 99441, dtype: int64

In [205]:
feature_engineered_path = p_dir.FEATURE_ENGINEERED

orders_df.to_csv(feature_engineered_path/'featured_orders.csv',index=False)

#####  merging the products and category_name tables on category name col

In [206]:


products_df = pd.read_csv(products,index_col=0)
products_df.sample(5)

category_name_df = pd.read_csv(category_name,index_col=0)
category_name_df = category_name_df.rename(columns={
    'product_category_name':'category_name',
    'product_category_name_english' : 'category_name_eng'
})
category_name_df.sample()

   category_name category_name_eng
58       bebidas            drinks

In [207]:
products_df.duplicated().sum()

np.int64(0)

In [208]:
products_df = products_df.merge(
    category_name_df[['category_name','category_name_eng']],
    on='category_name',
    how='left'
)

products_df.sample(5)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm,category_name_eng
17196,2d966327355281a1ff85f267e0d08781,eletrodomesticos,51.0,362.0,3.0,625.0,25.0,9.0,25.0,home_appliances
5611,5467bf450d0538e899a8e18fd0ff4323,utilidades_domesticas,45.0,520.0,1.0,350.0,16.0,15.0,15.0,housewares
7715,5cbecf1b44b9abf491a61aadf2809f1a,cama_mesa_banho,30.0,140.0,1.0,700.0,40.0,4.0,30.0,bed_bath_table
30160,2dda8afe04774afea003920be7d6fffb,cama_mesa_banho,55.0,699.0,1.0,1000.0,16.0,10.0,16.0,bed_bath_table
18993,8fcc1d90544dc9032e38da313cd5d278,consoles_games,43.0,117.0,1.0,180.0,21.0,6.0,17.0,consoles_games

In [209]:
products_df['volume'] = (products_df['length_cm'] * products_df['width_cm'] * products_df['height_cm'])

In [210]:
products_df = products_df.drop(['length_cm','width_cm','height_cm'],axis=1)
products_df.sample(5)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,category_name_eng,volume
7265,e2a1d45a73dc7f5a7f9236b043431b89,fashion_calcados,56.0,459.0,2.0,9000.0,fashion_shoes,2640.0
21336,25300f04b80a57680ca191c7d4ea64e1,beleza_saude,35.0,1125.0,1.0,100.0,health_beauty,1360.0
32031,4ed545d4c0dcea0798b3bafcd081ebff,esporte_lazer,51.0,1771.0,1.0,1080.0,sports_leisure,6080.0
2385,81b454070eecf89b21503cd5d313aa57,automotivo,50.0,2304.0,4.0,250.0,auto,1440.0
20456,2122804f6d118ffec73266ebf35e85d4,beleza_saude,25.0,740.0,1.0,1450.0,health_beauty,10875.0

In [211]:
products_df.columns

Index(['product_id', 'category_name', 'name_length', 'description_length',
       'photos_qty', 'weight_g', 'category_name_eng', 'volume'],
      dtype='str')

In [212]:
products_df.to_csv(feature_engineered_path/'featured_products.csv',index=0)

#### total spending by per customer

In [213]:
print(orders_items_df.sample(1))
# customers_df.sample(3)
# payments_df.sample(4)
orders_df.sample(4)

                               order_id  order_item_id  \
81601  b974b0392e8168e425f77abccf5563a4              1

                             product_id                         seller_id  \
81601  89de415e2cf869a6b1274f51913f1a49  0249d282d911d23cb8b869ab49c99f53

       shipping_limit_date  price  freight_value  total_amount
81601  2017-11-13 02:15:22   21.5           9.34         30.84

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer
68802,ef7a5dc729f1b870d114de326d4ab611,47c13b7b660f139c663f025db04ab57c,delivered,2017-09-29 13:14:55,2017-09-29 13:28:11,2017-09-29 20:36:01,2017-10-06 19:48:57,2017-10-27,7.0,-21.0,0,1af02f868fedbf83459c5c0603aa026b,1,0
93831,3f659c93a9c8600a0b0acf0eb42663d3,4d46e7275d4a252e48cb5c22cc7259b5,delivered,2017-11-23 12:20:19,2017-11-23 12:49:20,2017-11-23 20:46:38,2017-11-25 14:54:56,2017-12-07,2.0,-12.0,0,78f389ed9b9a7b052b14ed2afd698c07,1,0
77661,75f1f96566e2fbecc5fe22dd4f16f8e8,88d44020b4142f4668150bc2a3c9530d,delivered,2017-02-11 22:45:38,2017-02-11 22:55:16,2017-03-06 10:11:44,2017-03-17 12:08:17,2017-03-14,33.0,3.0,1,55845d91497951227fd70e450ffb35e0,1,0
48104,5000d08e089db4f432f3982d25f483de,2acd802c888c02c8d2b550a0c7b357d4,delivered,2018-07-01 19:51:47,2018-07-01 20:10:04,2018-07-03 08:55:00,2018-07-10 19:07:36,2018-07-27,8.0,-17.0,0,17b4caf45618845bac7a29610ee921ce,1,0

In [214]:
# joining the orders_df and orders_items_df on order_id

orders_df = orders_df.merge(
    orders_items_df[['order_id','total_amount']],
    on='order_id',
    how='left'
)

In [215]:
orders_df.sample(2)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,total_amount
21190,0b0809b2b64511c62fb745fb8b465cc9,56d6082f14bf0030bbc257ee81aaed82,delivered,2018-07-01 17:47:38,2018-07-01 17:55:13,2018-07-04 14:34:00,2018-07-06 17:22:09,2018-07-24,4.0,-18.0,0,47368842f3611a911ad776b043394ea1,1,0,46.80
89242,2c9dc43931bd73d816deb0582edff245,e7a5a238f60bebe0efe9ccbda1042ed5,delivered,2017-05-18 02:02:54,2017-05-18 02:15:34,2017-05-24 10:03:56,2017-06-02 13:03:22,2017-06-09,15.0,-7.0,0,15a4554642b5fe5a003bb9a7a2ec4893,1,0,149.16

In [216]:
orders_df['total_spending_by_cust'] = (orders_df.groupby('customer_unique_id')['total_amount'].transform('sum'))

In [217]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,total_amount,total_spending_by_cust
73288,7d962b9178f5ecd3d31dd69811311e65,2cf8fa6b9491168438f09e16f82fd543,delivered,2017-10-13 21:54:18,2017-10-13 22:07:09,2017-10-18 17:23:48,2017-10-24 16:29:59,2017-11-08,10.0,-15.0,0,5e173e3a61caee66b96f214a6e5bf4cc,1,0,61.01,183.03
6884,3e59aa9edece49294543e724d5a16f5f,85f25f8a9e0763a80ceeb2b63a3ab27b,delivered,2018-08-14 21:22:46,2018-08-14 21:30:26,2018-08-15 15:07:00,2018-08-21 21:22:49,2018-08-28,6.0,-7.0,0,6726866c9e7dbbac4a4954417a5e6149,1,0,132.46,132.46
30837,a72dab58dbb03b5509db9d29c658dc0d,0d507db4606f81ff5d5211c8d3047bdb,delivered,2017-12-24 00:05:52,2017-12-26 07:46:01,2017-12-26 21:33:34,2018-01-10 17:14:18,2018-01-30,15.0,-20.0,0,3279f77315e1f85892d965c2e0418225,1,0,29.09,58.18
23720,2936486c289152580e86cde8051de57c,be89c1031df2d31cf565eac6c699bf64,delivered,2017-12-29 21:41:00,2017-12-30 21:31:24,2018-01-03 17:10:58,2018-01-08 11:56:52,2018-01-26,8.0,-18.0,0,9070542e9f555b696dbaf24eb656fc4e,1,0,25.10,25.10
39639,6bc3c767bc73e1e4e1ba0670c3d90397,29e3dd4d4c101e8afb1f84aa611ec130,delivered,2018-02-26 16:19:39,2018-02-28 09:56:09,2018-02-28 21:25:17,2018-04-03 17:03:49,2018-03-16,34.0,18.0,1,3a6130b1b5ce0172f5ef08111138f8e3,1,0,97.01,97.01

In [218]:
sellers_df = pd.read_csv(sellers,index_col=0)
sellers_df.sample(5)
sellers_df['seller_id'].duplicated().sum()

np.int64(0)

In [219]:
orders_items_df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'total_amount'],
      dtype='str')

In [220]:
# total revenue by each seller 

orders_items_df.sample(5)
orders_items_df['seller_revenue'] = (orders_items_df.groupby('seller_id')['total_amount']).transform('sum')

In [221]:
# seller order count
orders_items_df['seller_order_count'] = (orders_items_df.groupby('seller_id')['product_id']).transform('count')

In [222]:
orders_items_df.sample(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count
106372,f1bc2e9a22c1bd86a33e5f04595f1bdd,1,7fb04722aba7a2b632bac8f9819796f3,f3b80352b986ab4d1057a4b724be19d0,2018-06-26 10:22:44,90.00,27.58,117.58,12692.73,92
34309,4d9bdec93e39b15084f7e5fac6e37c9c,1,6bf834c3fe86ab984f80c2914fef03e3,ac3508719a1d8f5b7614b798f70af136,2017-07-20 23:05:18,109.90,18.02,127.92,15792.23,104
56224,7feb540a28fa86db26a17648584a75d1,1,952670bc019a73f0933157ec82ff6e4f,37be5a7c751166fbc5f8ccba4119e043,2017-09-19 23:24:16,179.99,14.86,194.85,61433.88,281

In [223]:
orders_items_df.to_csv(feature_engineered_path/'featured_order_items.csv')