In [2]:
import pandas as pd
from configs.database import engine
from configs.settings import project_dir

1

In [3]:
p_dir = project_dir()
featured_dir = p_dir.FEATURE_ENGINEERED

In [4]:
featured_orders = featured_dir/'featured_order_items.csv'
foi_df = pd.read_csv(featured_orders,index_col=0)

In [5]:
foi_df.sample(4)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count
75797,ac9c563c1293db37e4a035f8ee3763db,1,fc5c33cddd49638580cfe9fec90aa943,a425f92c199eb576938df686728acd20,2017-12-14 16:48:39,85.0,15.34,100.34,1474.75,19
89449,cb2fbc8c6e48dc4954fc8cb1034900f0,1,89d49f6d10ff422902b2c2cb05da7f1c,9646c3513289980f17226a2fc4720dbd,2017-03-16 19:27:48,49.9,12.93,62.83,4247.32,78
30192,44900db49b182f4c5488152220bed716,1,78f03f51ef7a8e468dfe807ab205c9e5,bf00385a5f7fc1ef39a13c2e9ee50a5f,2018-08-08 08:44:45,59.9,24.77,84.67,1213.03,29
53478,79b63d1f9cf0257b33b04fbfb0847cba,1,0e669e3efedd9f3ab75fcbe334e1177e,9d4db00d65d7760644ac0c14edb5fd86,2018-03-29 21:48:33,129.8,12.24,142.04,11512.81,100

In [6]:
# storing the featured order items dataset to the database

foi_df.to_sql('featured_order_items',engine,if_exists='replace',index=False)

-1

In [7]:
# storing the featured products dataset to the database
featured_products = featured_dir/'featured_orders.csv'

In [8]:
fp_df = pd.read_csv(featured_products)
fp_df.sample(4)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,order_value,order_count,total_spending_by_cust,avg_order_value_count
7410,94fba1bfb7cfc7150d1b2a902bb4f14a,4e6c31afea698a7bceaecc399e3ba478,delivered,2018-05-08 10:59:08,2018-05-08 11:15:14,2018-05-10 19:07:00,2018-05-11 23:05:23,2018-05-16,3.0,-5.0,0.0,ef574e3866eb2704cb9b0345f84f9883,1,0,117.96,1.0,117.96,117.96
69102,6251915eca989de65a0d5bd949bb98fd,9d4f394cfc7fbf420201e20f14e87aac,delivered,2017-12-01 19:00:12,2017-12-01 19:30:59,2017-12-04 18:09:49,2017-12-19 00:22:46,2018-01-03,17.0,-15.0,0.0,defe4411ce1c0039696a89f179d3fbfa,1,0,140.49,1.0,140.49,140.49
90716,f4253eb9f34c40695de3f9f8e59d2875,de6cdc6367fdb29059cac3623a87b49d,delivered,2018-03-26 17:38:36,2018-03-26 17:50:20,2018-03-27 20:13:20,2018-03-28 21:27:52,2018-04-06,2.0,-9.0,0.0,da4ff019ca33b0c91844d880b6614c4f,1,0,56.78,1.0,56.78,56.78
46672,44653f1f97b2b55f4f96313c3ac8c5c0,56ae3795fc766069ee9a714e8434b9c8,delivered,2017-05-31 12:26:02,2017-05-31 13:10:25,2017-06-01 10:50:09,2017-06-06 15:16:10,2017-06-27,6.0,-21.0,0.0,cc613d652143b2cbe0e8e5faf6c15c98,1,0,117.94,1.0,117.94,117.94

In [9]:
fp_df.to_sql('featured_products',engine,if_exists='replace',index='False')

-1

In [15]:
cleaned_dir = p_dir.CLEANED_DIR

orders_items_df = cleaned_dir/'cleaned_orders_items.csv'

oid = pd.read_csv(orders_items_df,index_col=0)

In [12]:
fp_df.sample(3)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,order_value,order_count,total_spending_by_cust,avg_order_value_count
69378,bf95b3f726bbc62043afc14fbfdbcdec,57d501c72879ffdf6edd0e31c2e25eef,delivered,2018-03-05 15:39:48,2018-03-05 16:09:27,2018-03-08 20:04:47,2018-03-18 11:52:09,2018-03-22,12.0,-4.0,0.0,0da4c7d00921347054ca0be6b390dec7,1,0,121.09,1.0,121.09,121.09
40889,41028f6e5c0766a28665b78590b4b8d7,7795e422f21ee2057de57ef0212b4d7a,delivered,2018-04-02 21:31:12,2018-04-02 21:49:12,2018-04-04 21:46:47,2018-04-13 15:12:33,2018-04-23,10.0,-10.0,0.0,53b5f3ee447865c2de22e4814ef70bbe,1,0,277.52,1.0,277.52,277.52
19838,55966b3807b78c9c7eaf6a2c0c820abe,744ffbbbb5e51c8c5ea3f12cf97d7f8d,delivered,2017-07-14 22:02:51,2017-07-14 22:15:19,2017-07-21 18:32:57,2017-08-09 21:45:00,2017-08-14,25.0,-5.0,0.0,401f04c5c71087ab774f6db7b8297068,1,0,216.64,1.0,216.64,216.64

In [16]:
oid.to_sql('orders_items',engine,if_exists='replace',index=False)

-1

In [19]:
sellers = cleaned_dir/'cleaned_sellers.csv'
df_sellers = pd.read_csv(sellers,index_col=0)
df_sellers.sample(3)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2484,3078096983cf766a32a06257648502d1,13720,scao jose do rio pardo,SP
320,ce33c6211beaa8fef4cae8b52db39862,8655,suzano,SP
1489,f0b47fbbc6dee9aafe415a6e33051b3f,9360,maua,SP