## Applying Feature Engineering on our dataset

In [1]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [2]:
p_dir = project_dir()
clean_data_dir = p_dir.CLEANED_DIR

category_name = clean_data_dir/'category_name.csv'
customers = clean_data_dir/'clean_customers.csv'
location = clean_data_dir/'cleaned_location.csv'
order_payments = clean_data_dir/'cleaned_order_payments.csv'
orders_items = clean_data_dir/'cleaned_orders_items.csv'
order_reviews = clean_data_dir/'cleaned_order_reviews.csv'
orders = clean_data_dir/'cleaned_orders.csv'
products = clean_data_dir/'cleaned_products.csv'
sellers = clean_data_dir/'cleaned_sellers.csv'

In [3]:
orders_df = pd.read_csv(orders)
orders_df = orders_df.drop('Unnamed: 0',axis=1)
orders_df.sample(5)

payments_df = pd.read_csv(order_payments)
payments_df = payments_df.drop('Unnamed: 0',axis=1)
payments_df.sample(5)

orders_items_df = pd.read_csv(orders_items)
orders_items_df = orders_items_df.drop('Unnamed: 0',axis=1)
orders_items_df.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
23824,3645c66b5c03384bc97063c45b29acd7,1,b60aae43af64142e8dafff9888b64c85,7a67c85e85bb2ce8582c35f2203ad736,2017-09-26 02:35:36,239.99,17.93
61911,8d4defaad3d1206dde5189a813b794f2,1,4921779f44984246c74bba58ecf65146,4e922959ae960d389249c378d1c939f5,2018-03-05 03:36:46,690.00,20.59
54588,7c15b7f016feebc19af2f23f5f8b9e4a,1,9a63d4ef456702710823c21b8cca0332,817245bcc3badd82bbd222e0366951a6,2018-04-27 09:31:43,169.90,13.63
29728,43960d2cd4437218da00d3b8e83b2819,2,8e6e42a2047122de7ae174a7840125b1,0b18d63d0cd1d723567903fd34a07df2,2017-07-18 04:06:04,10.99,11.85
57473,82c46826f081404f1809ea22a81d293a,1,13cde3217a6ea7e5eb08bc8972ba9049,9d5a9018aee56acb367ba9c3f05d1d6a,2017-09-27 21:45:32,149.90,13.30

In [188]:
orders_items_df.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [4]:
## Creating a new columns of total amount of by doing sum of price and fright value
orders_items_df['total_amount'] = orders_items_df['price'] + orders_items_df['freight_value']

In [190]:
orders_items_df.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount
63892,91eef134a9dc65e566fde368f1772b93,1,727a46f0b58a9ef165af9f7ebcfebfa9,e9779976487b77c6d4ac45f75ec7afe9,2018-06-10 22:50:31,19.49,7.87,27.36
70523,a0f3677ac2cfd35a8d76f4a26fb29a95,1,e0d64dcfaa3b6db5c54ca298ae101d05,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-23 01:17:35,127.00,17.80,144.80
13541,1ecad0e8ea57760ebd5ea7863ec48b06,2,6e1b14d3cbb5fb3a2c00351007127dfd,7a67c85e85bb2ce8582c35f2203ad736,2017-08-04 07:15:12,229.99,17.24,247.23
6798,0f6665a373c36216e96163b3162404b0,1,c01cc7b6054e22d68972a35df1e0c249,a67780aba9dd436e7ac0aa1f889e73ec,2018-02-06 13:52:03,42.60,31.10,73.70
86901,c5585ae33ee215aeee0d7f9aaec67cde,2,9cb2ed2f273027b8daa3b0863368105c,76d5af76d0271110f9af36c92573f765,2017-12-05 02:20:00,39.90,16.11,56.01

In [191]:
orders_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_estimated_deliverey_date'],
      dtype='str')

In [7]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](4), str(4)
memory usage: 6.1 MB

In [5]:
# fixing the dtype
date_col = [
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_col:
    orders_df[col] = pd.to_datetime(orders_df[col])

In [195]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](4), str(4)
memory usage: 6.1 MB

In [6]:

# creating a new columns in orders_df delivery_days usig order_purchase_timestamp and order_delivered-customer_date
orders_df = orders_df.rename(
    columns={
        'order_purchase_timestamp' : 'order_purchase',
        'order_approved_at' : 'approved_at',
        'order_delivered_carrier_date' : 'delivered_carrier_date',
        'order_delivered_customer_date' : 'delivered_customer_date',
        'order_estimated_delivery_date' : 'estimated_delivery_date'
    }
)



orders_df['delivery_days'] = (orders_df['delivered_customer_date'] - orders_df['approved_at']).dt.days
# orders_df.sample(5)

In [7]:
# adding a new columns delivery_delay

orders_df ['delivery_delay_days'] = (orders_df['delivered_customer_date'] - orders_df['estimated_delivery_date']).dt.days

# orders_df = orders_df.drop('delivery_delay',axis=1)

# adding a new columns is_delayed 
delivery_mask = orders_df['order_status'] == 'delivered'

orders_df['is_delayed'] = np.nan
# orders_df['is_delayed'] = (orders_df['estimated_delivery_date'] < orders_df['delivered_customer_date']).astype(int)

orders_df.loc[delivery_mask,'is_delayed'] = (
    orders_df.loc[
        delivery_mask, 'delivered_customer_date'
    ] > orders_df.loc[
        delivery_mask, 'estimated_delivery_date'
    ]
).astype(int)

In [25]:
orders_df['order_status'].value_counts()

order_status
delivered      110197
shipped          1186
canceled          706
unavailable       610
invoiced          361
processing        357
created             5
approved            3
Name: count, dtype: int64

In [8]:
orders_df.loc[
    orders_df['order_status'] != 'Invoiced','is_delayed'
].value_counts()

# orders_df.loc[orders_df['order_status'] != 'delivered', 'is_delayed'].value_counts()

is_delayed
0.0    88652
1.0     7826
Name: count, dtype: int64

In [9]:
orders_df['is_delayed'].value_counts(dropna=False)

is_delayed
0.0    88652
1.0     7826
NaN     2963
Name: count, dtype: int64

In [26]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,total_amount
11580,a5b431090739891ac76875d9ad9bff23,b769ee1c67d0e4f3c5b0abe1a1b958d4,delivered,2017-02-20 19:21:23,2017-02-20 19:35:09,2017-02-22 10:02:03,2017-02-24 08:08:06,2017-03-17,3.0,-21.0,0.0,232.05
59543,69f5eed47613a9d3cd0ae94d398cdd4e,af65b5fb2830e00789e56d7b30e86b63,delivered,2017-07-14 10:40:15,2017-07-14 10:50:22,2017-07-17 17:38:11,2017-07-24 19:51:23,2017-08-07,10.0,-14.0,0.0,55.05
67088,2d33e2f321b7f676de5d3ab87c08d1ab,ffbc52ac99e6184f3961fd791be5ff62,delivered,2017-08-06 22:07:14,2017-08-06 23:03:18,2017-08-07 17:03:09,2017-08-15 16:03:37,2017-08-31,8.0,-16.0,0.0,51.39
70197,81bee7ecbeae8e9b41bef6d41b146b12,e30b9a646ef5cf66d213d172db4d402f,delivered,2017-03-15 22:26:48,2017-03-15 22:26:48,2017-03-21 11:34:34,2017-03-27 18:14:00,2017-04-05,11.0,-9.0,0.0,101.13
3563,a8098c74d0b6846c8dd5ea90952879ce,0dfc0621220f4aa19960d5c5397f0835,delivered,2017-07-14 13:10:50,2017-07-14 13:24:16,2017-07-14 23:29:34,2017-07-24 21:06:02,2017-08-07,10.0,-14.0,0.0,36.60

In [10]:
customers_df = pd.read_csv(customers,index_col=0)
customers_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [11]:
# merging customers and orders tables
orders_df = orders_df.merge(
    customers_df[['customer_id','customer_unique_id']],
    on='customer_id',
    how='left'
)

orders_df.duplicated().sum()

np.int64(0)

In [12]:
orders_df['customer_order_count'] =orders_df.groupby('customer_unique_id')['order_id'].transform('count')

In [13]:
orders_df['customer_order_count'].value_counts()

# adding bool columns bout is it a repeat customer
orders_df['is_repeat_customer'] = (orders_df['customer_order_count'] > 1).astype(int)

In [203]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer
64342,352d885bc141f75e361bbf6501513d25,8f458f1a3f921406c1dda20db858fb40,delivered,2018-03-20 12:22:25,2018-03-20 12:35:22,2018-03-27 00:12:21,2018-03-31 19:53:42,2018-04-02,11.0,-2.0,0,9e45e105f9d3bbd65e327127e0a71a55,1,0
19739,f6bfc9902c58791929c6ba9af3953696,e6305a0a9355e91aad86e234263a41aa,delivered,2017-05-07 13:46:44,2017-05-07 14:02:15,2017-05-08 11:45:00,2017-05-17 11:12:37,2017-05-31,9.0,-14.0,0,ff4b2772a9368e8b30a1ebd484de12c9,1,0
94331,6e7e891760708803a2f4203981f2d69d,9bc1b48bb57b22ba2fbd77579dad8202,unavailable,2017-02-16 19:43:11,2017-02-16 19:55:17,NaT,NaT,2017-03-17,NaN,NaN,0,b3c3ded83fde176416890b31406e2415,1,0
31071,8c33d668c93faeb68c9fbf5fadd93e3a,f65a9d5dc0c49064efc04ca1d4667935,delivered,2017-04-23 11:33:03,2017-04-23 11:42:10,2017-04-25 08:47:25,2017-05-11 12:29:50,2017-05-30,18.0,-19.0,0,5d622f341bd6b5e3d07c22484f869f4f,1,0
92772,95617572e4e39b8b9f5384d136111f93,1801ef99dbe925417e3103f8adafb25a,delivered,2018-02-03 09:59:51,2018-02-03 10:33:40,2018-02-05 23:33:53,2018-02-20 16:07:14,2018-03-08,17.0,-16.0,0,7d03dbebae935f56b7df8bb280aaaa15,1,0

In [14]:
# total spending per customer

orders_df.groupby('customer_unique_id')['order_id'].transform('count')

0        2
1        1
2        1
3        1
4        1
        ..
99436    1
99437    1
99438    1
99439    1
99440    1
Name: order_id, Length: 99441, dtype: int64

In [15]:
feature_engineered_path = p_dir.FEATURE_ENGINEERED

orders_df.to_csv(feature_engineered_path/'featured_orders.csv',index=False)

#####  merging the products and category_name tables on category name col

In [16]:


products_df = pd.read_csv(products,index_col=0)
products_df.sample(5)

category_name_df = pd.read_csv(category_name,index_col=0)
category_name_df = category_name_df.rename(columns={
    'product_category_name':'category_name',
    'product_category_name_english' : 'category_name_eng'
})
category_name_df.sample()

   category_name category_name_eng
60    la_cuisine        la_cuisine

In [207]:
products_df.duplicated().sum()

np.int64(0)

In [17]:
products_df = products_df.merge(
    category_name_df[['category_name','category_name_eng']],
    on='category_name',
    how='left'
)

products_df.sample(5)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm,category_name_eng
16266,5355a40d35bd884a0a357a703be19df5,market_place,48.0,1022.0,4.0,100.0,27.0,15.0,15.0,market_place
12578,d5ad2be418dec48e9d0c4745e431c384,informatica_acessorios,43.0,893.0,1.0,150.0,21.0,11.0,12.0,computers_accessories
16141,3ad77ee47938193d6240dadba0feeaa0,perfumaria,48.0,1067.0,2.0,419.0,20.0,17.0,20.0,perfumery
28608,c54fe6aa647b1835911c540439f62300,climatizacao,59.0,250.0,4.0,5150.0,36.0,47.0,46.0,air_conditioning
94,64c8f1a52b407d92518a1f8b79240a70,telefonia,49.0,319.0,1.0,100.0,18.0,6.0,11.0,telephony

In [18]:
products_df['volume'] = (products_df['length_cm'] * products_df['width_cm'] * products_df['height_cm'])

In [19]:
products_df = products_df.drop(['length_cm','width_cm','height_cm'],axis=1)
products_df.sample(5)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,category_name_eng,volume
23912,65ffac7c6e6c38822b7fa3f801511114,dvds_blu_ray,33.0,668.0,1.0,200.0,dvds_blu_ray,560.0
26143,a0b706aace06abff783f614e8b01b760,beleza_saude,32.0,461.0,1.0,500.0,health_beauty,4864.0
29924,1f13ebbc80d3713a1abdd12696605956,consoles_games,57.0,799.0,1.0,775.0,consoles_games,15225.0
25779,afe60f026d04f54945ecf4c085eff7f5,informatica_acessorios,56.0,235.0,1.0,633.0,computers_accessories,4056.0
1669,187359f629249d5333ce31f87136a802,utilidades_domesticas,43.0,1437.0,7.0,900.0,housewares,15360.0

In [211]:
products_df.columns

Index(['product_id', 'category_name', 'name_length', 'description_length',
       'photos_qty', 'weight_g', 'category_name_eng', 'volume'],
      dtype='str')

In [20]:
products_df.to_csv(feature_engineered_path/'featured_products.csv',index=0)

#### total spending by per customer

In [213]:
print(orders_items_df.sample(1))
# customers_df.sample(3)
# payments_df.sample(4)
orders_df.sample(4)

                               order_id  order_item_id  \
81601  b974b0392e8168e425f77abccf5563a4              1

                             product_id                         seller_id  \
81601  89de415e2cf869a6b1274f51913f1a49  0249d282d911d23cb8b869ab49c99f53

       shipping_limit_date  price  freight_value  total_amount
81601  2017-11-13 02:15:22   21.5           9.34         30.84

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer
68802,ef7a5dc729f1b870d114de326d4ab611,47c13b7b660f139c663f025db04ab57c,delivered,2017-09-29 13:14:55,2017-09-29 13:28:11,2017-09-29 20:36:01,2017-10-06 19:48:57,2017-10-27,7.0,-21.0,0,1af02f868fedbf83459c5c0603aa026b,1,0
93831,3f659c93a9c8600a0b0acf0eb42663d3,4d46e7275d4a252e48cb5c22cc7259b5,delivered,2017-11-23 12:20:19,2017-11-23 12:49:20,2017-11-23 20:46:38,2017-11-25 14:54:56,2017-12-07,2.0,-12.0,0,78f389ed9b9a7b052b14ed2afd698c07,1,0
77661,75f1f96566e2fbecc5fe22dd4f16f8e8,88d44020b4142f4668150bc2a3c9530d,delivered,2017-02-11 22:45:38,2017-02-11 22:55:16,2017-03-06 10:11:44,2017-03-17 12:08:17,2017-03-14,33.0,3.0,1,55845d91497951227fd70e450ffb35e0,1,0
48104,5000d08e089db4f432f3982d25f483de,2acd802c888c02c8d2b550a0c7b357d4,delivered,2018-07-01 19:51:47,2018-07-01 20:10:04,2018-07-03 08:55:00,2018-07-10 19:07:36,2018-07-27,8.0,-17.0,0,17b4caf45618845bac7a29610ee921ce,1,0

In [21]:
# joining the orders_df and orders_items_df on order_id

order_total = orders_items_df.groupby('order_id').agg(
    order_value = ('total_amount','sum'),
    order_count = ('order_item_id','count')
)

# order_total['order_count'].value_counts()

In [22]:
orders_df = orders_df.merge(
    order_total,on='order_id',how='left'
)

In [23]:
print(len(orders_df), orders_df['order_id'].nunique(), orders_df['order_id'].duplicated().sum())

99441 99441 0

In [43]:
orders_df.sample(2)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,total_amount,order_value,order_count
58125,53c33e360f83136bc4328eda17c360fd,3491de3df74d53eb01943cbf73a4199b,delivered,2017-06-16 19:05:07,2017-06-18 11:55:15,2017-06-19 18:43:37,2017-06-28 10:22:39,2017-07-10,9.0,-12.0,0.0,206.98,206.98,1.0
53616,8e029d51bb988ddd1e92385dce8de59a,b6ee22d5dbe6ff4f160e31c63e97215a,delivered,2018-07-24 20:45:16,2018-07-24 21:05:09,2018-07-26 11:55:00,2018-08-01 16:16:49,2018-08-07,7.0,-6.0,0.0,432.18,432.18,1.0

In [24]:
orders_df['total_spending_by_cust'] = (orders_df.groupby('customer_unique_id')['order_value'].transform('sum'))
orders_df['avg_order_value_count'] = (orders_df.groupby(
    'customer_unique_id'
)['order_value'].transform( 'mean')

)

In [25]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase,approved_at,delivered_carrier_date,delivered_customer_date,estimated_delivery_date,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,order_value,order_count,total_spending_by_cust,avg_order_value_count
71105,3139d2c500d282f1549eb3c6e7723985,5be865cd6c0d8f82203de5f4d0b3409b,delivered,2018-07-16 16:07:48,2018-07-18 02:50:19,2018-07-18 12:23:00,2018-07-26 18:14:32,2018-08-07,8.0,-12.0,0.0,2a1dd58d2b2c5131c77f51da5e409c2c,1,0,291.94,1.0,291.94,291.94
11381,4d0f637afbd692c3e9fbffbc338de497,42c1788dfeabff14c5032eaa426b30c5,delivered,2018-08-21 15:43:35,2018-08-21 15:55:15,2018-08-22 14:29:00,2018-08-23 22:03:23,2018-08-24,2.0,-1.0,0.0,618114fa5e560b9573797987c2fdf820,1,0,138.28,2.0,138.28,138.28
40064,553ca0a1ff1834f49d15d77ac8d08ca8,b85cfeeb9135227e8ba9a25eaf173872,delivered,2018-04-15 22:05:57,2018-04-15 22:29:53,2018-04-17 23:11:02,2018-04-23 22:22:00,2018-05-15,7.0,-22.0,0.0,69b3aee0b28c396c57797a12a9a15db9,1,0,123.18,1.0,123.18,123.18
97075,3e84781202afaaf7f60c916ead71766e,4e0e75fc56e2609aa885d4305d4d07fe,delivered,2018-04-09 14:34:07,2018-04-09 14:50:45,2018-04-10 20:22:26,2018-04-13 20:58:56,2018-04-26,4.0,-13.0,0.0,4dd66f4040bb1d6e487ea25b30bdf7fe,1,0,68.64,1.0,68.64,68.64
5358,669680ec0096baf96bb966401209e3f3,541b98cb6ebd8e11ee8508bb7e6fedb9,delivered,2018-07-26 17:49:11,2018-07-26 18:24:00,2018-07-27 09:49:00,2018-08-02 00:42:52,2018-08-17,6.0,-15.0,0.0,a2dfb6300b6b54d58dd005d415dde92b,1,0,193.84,1.0,193.84,193.84

In [218]:
sellers_df = pd.read_csv(sellers,index_col=0)
sellers_df.sample(5)
sellers_df['seller_id'].duplicated().sum()

np.int64(0)

In [219]:
orders_items_df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'total_amount'],
      dtype='str')

In [26]:
# total revenue by each seller 

orders_items_df.sample(5)
orders_items_df['seller_revenue'] = (orders_items_df.groupby('seller_id')['total_amount']).transform('sum')

In [27]:
# seller order count
orders_items_df['seller_order_count'] = (orders_items_df.groupby('seller_id')['product_id']).transform('count')

In [222]:
orders_items_df.sample(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count
106372,f1bc2e9a22c1bd86a33e5f04595f1bdd,1,7fb04722aba7a2b632bac8f9819796f3,f3b80352b986ab4d1057a4b724be19d0,2018-06-26 10:22:44,90.00,27.58,117.58,12692.73,92
34309,4d9bdec93e39b15084f7e5fac6e37c9c,1,6bf834c3fe86ab984f80c2914fef03e3,ac3508719a1d8f5b7614b798f70af136,2017-07-20 23:05:18,109.90,18.02,127.92,15792.23,104
56224,7feb540a28fa86db26a17648584a75d1,1,952670bc019a73f0933157ec82ff6e4f,37be5a7c751166fbc5f8ccba4119e043,2017-09-19 23:24:16,179.99,14.86,194.85,61433.88,281

In [223]:
orders_items_df.to_csv(feature_engineered_path/'featured_order_items.csv')

In [55]:
len(orders_df), orders_df['order_id'].nunique()

(113425, 99441)

In [56]:
orders_df['order_value'].describe()

count    112650.000000
mean        180.244628
std         272.829911
min           9.590000
25%          65.620000
50%         114.440000
75%         195.337500
max       13664.080000
Name: order_value, dtype: float64

In [28]:
orders_df.to_csv(feature_engineered_path/'featured_orders.csv',index=False)

In [29]:
from configs.database import engine
orders_df.to_sql('featured_orders',engine,if_exists='append',index=False)

-1

In [30]:
len(orders_df), orders_df['order_id'].nunique()

(99441, 99441)

In [31]:
orders_df['order_value'].describe()

count    98666.000000
mean       160.577638
std        220.466087
min          9.590000
25%         61.980000
50%        105.290000
75%        176.870000
max      13664.080000
Name: order_value, dtype: float64