# Data Cleaning

In [1]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [2]:
p_dir = project_dir()

raw_data_dir =  p_dir.RAW_DATA_DIR

orders = raw_data_dir/'olist_orders_dataset.csv'
products = raw_data_dir/'olist_products_dataset.csv'
sellers = raw_data_dir/'olist_sellers_dataset.csv'
category = raw_data_dir /'product_category_name_translation.csv'

In [3]:
cleaned_data_dir = p_dir.CLEANED_DIR

## Orders table cleaning

In [168]:
orders_df = pd.read_csv(orders)
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
42865,6113734f28c4dd1490de62945a9adf43,9c8f4989367caf5cc9fc08254f3ef547,delivered,2017-11-29 22:59:41,2017-11-29 23:17:58,2017-12-15 01:33:19,2017-12-28 19:39:05,2018-01-15 00:00:00
40001,024a74550cdbd36c0fe3955fc9e2bcf0,5837b288ad076175ff451a905d6153f9,delivered,2018-08-09 08:10:23,2018-08-09 08:50:19,2018-08-14 14:42:00,2018-08-15 18:28:43,2018-08-14 00:00:00
13626,31593a3048f6d0e061a4101a6e5fe24f,b6623d5bf68c77aaaa0033d082ef2e96,delivered,2017-10-05 09:53:37,2017-10-05 10:07:21,2017-10-05 17:49:01,2017-10-16 19:15:44,2017-11-03 00:00:00
86144,d646d163f7d7fceab2954628f695a033,0600e7baad27ff0e4791e270351cccf1,delivered,2017-11-07 18:39:46,2017-11-07 18:50:40,2017-11-09 19:45:55,2017-11-20 17:52:52,2017-11-29 00:00:00
1585,f6cbd0bea76d160391128a43b629ae9f,7e513111ace41e153422909d22223677,delivered,2017-02-16 09:42:48,2017-02-16 09:50:25,2017-02-17 13:34:38,2017-03-02 14:09:17,2017-03-17 00:00:00

In [169]:
print(orders_df.info())
print(orders_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [170]:
# fixing the date type columns
orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_deliverey_date']] = orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].astype('datetime64[ns]')

In [171]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
11631,92e3415f60fec80f07ebca939434c3a7,85163f5cd854d552b1627f12e52721fc,delivered,2017-01-27 10:29:59,2017-01-27 10:41:54,2017-01-31 11:50:54,2017-02-02 17:43:58,2017-03-03 00:00:00,2017-03-03
73022,7e4b03dd0033e5b679e258243d9df206,664c19a838d368c81b12d20087ae22b9,delivered,2017-08-30 12:28:36,2017-08-31 02:50:43,2017-08-31 21:12:47,2017-09-11 16:09:06,2017-09-20 00:00:00,2017-09-20
23509,d470b00bc3d705453cd02a793aaddb07,0b66eb99b1af5a704c8bb97390d2ea76,delivered,2017-07-21 02:13:24,2017-07-21 02:22:47,2017-07-24 10:43:58,2017-07-29 10:55:35,2017-08-15 00:00:00,2017-08-15
6660,af88a4bca5075cdda8da09cc6c55635f,8dda2c8532448b7a942c8ffc3800b0ed,delivered,2017-11-24 19:18:57,2017-11-24 22:36:27,2017-12-01 15:58:51,2017-12-19 21:14:32,2017-12-15 00:00:00,2017-12-15
59256,5ac4eee743a86a4f0d1b7ee150d1bb34,bc64e5a7d927cba23c4b58e8c417c2f9,delivered,2017-11-26 00:10:06,2017-11-26 00:32:47,2017-11-29 23:24:46,2017-12-27 11:47:59,2017-12-22 00:00:00,2017-12-22

In [172]:
## handling the missing values 

orders_df[orders_df['order_delivered_carrier_date'].isna()].sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
14460,2e9d8db9e132a9b5e1236618b7e8ef4a,51c6f517f4492a9c2ab4153e998b018e,canceled,2018-08-09 18:42:38,NaT,NaT,NaT,2018-09-04 00:00:00,2018-09-04
26445,2e935fa1d39497aa0ec3f1107fbfb5b8,ffffe8b65bbe3087b653a978c870db99,unavailable,2017-09-29 14:07:03,2017-10-03 06:34:13,NaT,NaT,2017-10-24 00:00:00,2017-10-24
46093,29380cfab5f9f5f233e2c71e16cadc68,a1774d98db8380cc69ef842c759be95f,unavailable,2018-05-09 16:55:09,2018-05-09 17:15:15,NaT,NaT,2018-05-28 00:00:00,2018-05-28
20681,5461b16bc5220279efdefe1dba3db81e,2acc0aa04c8ea6b0378fdb3928cd819a,invoiced,2018-03-13 14:36:36,2018-03-14 15:00:23,NaT,NaT,2018-04-02 00:00:00,2018-04-02
39919,4637ca194b6387e2d538dc89b124b0ee,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaT,NaT,NaT,2018-09-10 00:00:00,2018-09-10
62133,9e99d6f656fcb2d4a76e9455959cf62f,8c2cacdb29d403b18d70caabdad611bc,invoiced,2017-09-12 08:25:21,2017-09-12 08:35:15,NaT,NaT,2017-09-22 00:00:00,2017-09-22
33509,7ecb6c38b166531663fdecce49dc1a6f,288f90dc3b55afaff2904553fa5cbfe0,unavailable,2017-12-29 00:18:54,2017-12-30 00:11:18,NaT,NaT,2018-01-26 00:00:00,2018-01-26
2198,533e104c4193cf07d264603f7800fb71,2f95fc8f86679d432d77e9d0316fac48,processing,2017-02-06 15:33:57,2017-02-06 15:42:27,NaT,NaT,2017-03-03 00:00:00,2017-03-03
71737,9f24a452d2f08d94503f8755cc845362,825803c33fe215e80ac490cc7ea55813,unavailable,2017-09-04 02:26:00,2017-09-04 22:30:15,NaT,NaT,2017-10-03 00:00:00,2017-10-03
65891,055f84fd2ebf314ebec85f8e1312f4f4,82ff01ff3cdbae8ef85c10481d360d1a,processing,2018-01-13 17:32:09,2018-01-15 10:10:50,NaT,NaT,2018-02-14 00:00:00,2018-02-14

In [173]:
orders_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [174]:
orders_df.duplicated().sum()

np.int64(0)

#### handling the missing dates

In [175]:
orders_df[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].isna().sum()

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [176]:
orders_df[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date','order_status']].groupby('order_status').value_counts().to_string('../arson/order_status_date.csv')

In [177]:
orders_df.groupby('order_status')[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date']].apply(
    lambda x: x.isnull().sum()
)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609


## Products Dataset Cleaning

In [178]:
products_df = pd.read_csv(products)
products_df.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
27735,61a4100ccd6d9c4c808a1fd954ddb8ad,eletroportateis,60.0,3839.0,4.0,1450.0,24.0,24.0,24.0
18844,5a286d54a7400c4a0921c6e99300d684,informatica_acessorios,36.0,135.0,2.0,85.0,15.0,10.0,15.0
5902,8c0fd3e89ebf51f2fcff46abbc4eca05,relogios_presentes,40.0,525.0,3.0,500.0,38.0,12.0,38.0
26918,1e2c4845a09f960ea8b021fa72d98006,eletrodomesticos,58.0,130.0,1.0,300.0,18.0,8.0,13.0
15711,8f1138aa9a4a3c0127a10b19fe956cee,cama_mesa_banho,51.0,383.0,1.0,1150.0,37.0,9.0,30.0
77,0d009643171aee696f4733340bc2fdd0,perfumaria,52.0,150.0,1.0,422.0,21.0,16.0,18.0
26877,7ab21257ee876b3897bd55046d3d81d3,brinquedos,44.0,1450.0,1.0,683.0,31.0,25.0,24.0
23060,b1448ab856adbb8dc6ea2ba9489f555a,industria_comercio_e_negocios,48.0,729.0,1.0,16650.0,30.0,18.0,24.0
23946,4d53c4c283619d61ff3638ec8e2854d3,cama_mesa_banho,56.0,905.0,5.0,1550.0,32.0,6.0,25.0
7251,060965aa6dfa817b80abda0c9413cc77,cama_mesa_banho,59.0,3863.0,5.0,22250.0,85.0,23.0,68.0

In [179]:
products_df.info()
# TO-DO : fix columns name

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [180]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [181]:
products_df.duplicated().sum()

np.int64(0)

In [182]:
products_df['product_category_name'].value_counts().to_string('../arson/product_category.csv') ## question to ask, why there are no NaN values in my arson folder of this query.
products_df[products_df['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [183]:
# dropping missing values. 
products_df = products_df.dropna()

In [184]:
print(products_df.shape)
products_df.isnull().sum()

(32340, 9)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [185]:
products_df = products_df.rename(columns={
    'product_category_name': 'category_name',
    'product_name_lenght' : 'name_length',
    'product_description_lenght' : 'description_length',
    'product_photos_qty' : 'photos_qty',
    'product_weight_g' : 'weight_g',
    'product_length_cm' : 'length_cm',
    'product_height_cm' : 'height_cm',
    'product_width_cm' : 'width_cm'
})
products_df.sample(10)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm
10223,c8d90cfcce13c0471dc483876a080e87,telefonia,50.0,599.0,1.0,275.0,18.0,4.0,12.0
1037,a669398f595527fc03acc1ebda6b3cce,beleza_saude,58.0,905.0,2.0,300.0,20.0,10.0,15.0
31439,228f57b1acb5bdce9401c58653c8cc14,relogios_presentes,39.0,542.0,1.0,433.0,21.0,12.0,16.0
12528,e91f88846bc20e4ae032b9bacecaa625,utilidades_domesticas,19.0,388.0,3.0,425.0,23.0,23.0,23.0
14790,60377afd6f6da838f980b2522636cc22,bebes,42.0,1287.0,2.0,10250.0,55.0,38.0,43.0
10591,626f55dacc29e4f934bdb3e4f3be83b4,construcao_ferramentas_ferramentas,46.0,310.0,1.0,2025.0,32.0,15.0,22.0
22834,284baaa8749f5600668aa5e042689bfb,automotivo,60.0,1126.0,1.0,183.0,17.0,8.0,16.0
22228,1a7340927178189657dfa923be3bfdda,telefonia,58.0,777.0,6.0,150.0,17.0,4.0,12.0
24310,7dfced4c66ef7bd85f2e30eec92e1b34,moveis_decoracao,58.0,1878.0,2.0,1600.0,60.0,14.0,14.0
4958,d58118713a21b8177e844c58eb83efe7,utilidades_domesticas,59.0,212.0,2.0,500.0,36.0,10.0,13.0

In [186]:
products_df.to_csv(cleaned_data_dir/'cleaned_products.csv')

## Sellers Dataset cleaning

In [4]:
sellers_df = pd.read_csv(sellers)
sellers_df.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2119,6562efe88ce0826a4ca4f189f03b4b84,87005,maringa,PR
388,0d33a55da925bbf1ff02af5f6059fc7f,5632,sao paulo,SP
1541,e62b2d6ac10570a035a30bafcf01d263,5767,sao paulo,SP
2328,de23c3b98a88888289c6f5cc1209054a,5530,sao paulo,SP
1336,bd65d163ded559eb90a10cd09fec178f,3526,sao paulo,SP
1972,df0f42bc4c2142eacf0eaf2cffd0cfbb,88306,itajai,SC
2460,8ae520247981aa06bc94abddf5f46d34,88370,navegantes,SC
607,83d458c0d6d4f94295d63f091460bd60,29101,vila velha,SP
1681,a89e143d5211473ae18db9577ee34b64,13486,limeira,SP
768,20d83f3ef0e6925fd74bfd59170babf7,2804,sao paulo,SP

In [188]:
sellers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [189]:
sellers_df.duplicated().sum()

np.int64(0)

In [190]:
sellers_df.groupby('seller_city')[['seller_state','seller_zip_code_prefix']].value_counts().to_string('../arson/sellers_state.csv')

In [191]:
# Question to ask: how to handle the invalid values in sellers_city columns

In [192]:
orders_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_estimated_deliverey_date'],
      dtype='str')

In [193]:
orders_df.groupby('order_status')[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date']].apply(
    lambda x : x.isnull().sum()
)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [194]:
orders_df = orders_df.drop('order_estimated_deliverey_date',axis=1)
orders_df.to_csv(cleaned_data_dir/'cleaned_orders.csv')

In [195]:
orders_df['order_estimated_delivery_date'] = pd.to_datetime(orders_df['order_estimated_delivery_date'])

In [196]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[ns](4), datetime64[us](1), str(3)
memory usage: 6.1 MB

In [197]:
sellers_df.to_csv(cleaned_data_dir/'cleaned_sellers.csv')

In [7]:
customers = cleaned_data_dir/'clean_customers.csv'
customers_df = pd.read_csv(customers,index_col=0)
customers_df['customer_unique_id'].duplicated().sum()

np.int64(3345)

In [5]:
from configs.database import engine

# orders_df.to_sql('orders',engine,if_exists='append', index=False)

1

In [200]:
print(customers_df.info())
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[ns](4), datetime64[us](1), str(3)
memory usage: 6.1 MB

In [ ]:
customers_df.to_sql('customers',engine,if_exists='replace',index=False)

In [ ]:
orders_df.to_sql('orders',engine, if_exists='append',index=False)

-1

order_items df to postgresql

In [ ]:
order_items = cleaned_data_dir/'cleaned_orders_items.csv'
order_items_df = pd.read_csv(order_items,index_col=0)
order_items_df.columns

order_items_df.to_sql('order_items',engine,if_exists='append',index=False)

-1

### Sellers df to postgreSQL

In [ ]:
# sellers dataset
sellers_df.columns
sellers_df = sellers_df.rename(
    columns={
        'seller_zip_code_prefix' : 'seller_zip_code'
    }
)
sellers_df.to_sql('sellers',engine,if_exists='append',index=False)

-1

# storing category_name df to postgreSQL

In [ ]:
category_name = cleaned_data_dir/'category_name.csv'
category_name_df = pd.read_csv(category_name,index_col=0)
category_name_df.columns

category_name_df = category_name_df.rename(
    columns={
        'product_category_name' : 'category_name',
        'product_category_name_english' : 'category_name_eng'
    }
)

# category_name_df.to_sql('category_name',engine,if_exists='append',index=False)

In [ ]:
products = cleaned_data_dir/'cleaned_products.csv'
products_df = pd.read_csv(products,index_col=0)
# products_df

## storing products_df to postgresql

In [ ]:
common_categories = set(category_name_df['category_name'].dropna())
# common_categories.shape
# products_df['category_name'].value_counts()
products_df['category_name'] = products_df['category_name'].apply(
    lambda x : x if x in common_categories else None
)

In [ ]:
products_df.columns
# products_df = products_df.rename(
#     columns={
#         ''
#     }
# )
# products_df.to_sql('products',engine, if_exists='append',index=False)

Index(['product_id', 'category_name', 'name_length', 'description_length',
       'photos_qty', 'weight_g', 'length_cm', 'height_cm', 'width_cm'],
      dtype='str')

In [ ]:
products_df['category_name'].value_counts()

category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
tablets_impressao_imagem            9
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 71, dtype: int64

In [ ]:
products_df.to_sql('products',engine,if_exists='append',index=False)

-1

### storing location to postgreSQL

In [ ]:
locations = cleaned_data_dir/'cleaned_location.csv'
location_df = pd.read_csv(locations,index_col=0)
location_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 718463 entries, 0 to 718462
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   zip_code    718463 non-null  int64
 1   lat         718463 non-null  float64
 2   lng         718463 non-null  float64
 3   state       718463 non-null  str
 4   city_clean  718463 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 27.4 MB

In [ ]:
location_df = location_df.rename(
    columns={
        'lat' : 'geo_lat',
        'lng' : 'geo_lng',
        'city_clean' : 'city'
    }
)

In [ ]:
location_df.to_sql('location',engine,if_exists='append',index=False)

-1

### order_payments to postgre SQL

In [ ]:
orders_payment = cleaned_data_dir/'cleaned_order_payments.csv'
orders_payment_df = pd.read_csv(orders_payment,index_col=0)
orders_payment_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [ ]:
orders_payment_df = orders_payment_df.rename(
    columns={
        'payment_installments' : 'payment_emi',
        'payment_value' : 'amount'
    }
)

In [ ]:
orders_payment_df.to_sql('order_payments',engine, if_exists='append',index=False)

-1

### orders_reviews to postgresql

In [ ]:
order_reviews = cleaned_data_dir/'cleaned_order_reviews.csv'
order_reviews_df = pd.read_csv(order_reviews,index_col=0)
order_reviews_df.info()

<class 'pandas.DataFrame'>
Index: 98410 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                98410 non-null  str
 1   order_id                 98410 non-null  str
 2   review_score             98410 non-null  int64
 3   review_comment_title     98410 non-null  str
 4   review_comment_message   98410 non-null  str
 5   review_creation_date     98410 non-null  str
 6   review_answer_timestamp  98410 non-null  str
 7   has_comment              98410 non-null  bool
dtypes: bool(1), int64(1), str(6)
memory usage: 6.1 MB

In [ ]:
order_reviews_df = order_reviews_df.rename(
    columns={
        'review_creation_date' : 'creation_date'
    }
)
order_reviews_df['creation_date'] = pd.to_datetime(order_reviews_df['creation_date'])
order_reviews_df['review_answer_timestamp'] = pd.to_datetime(order_reviews_df['review_answer_timestamp'])

In [202]:
order_reviews_df.to_sql('order_reviews',engine,if_exists='append',index=False)

-1

### order_items to postgreSQL

In [203]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [204]:
order_items_df['shipping_limit_date'] = pd.to_datetime(
    order_items_df['shipping_limit_date']
)

In [206]:
order_items_df.to_sql(
    'orders_items',engine,if_exists='append',index=False
)

error ignored terminating <psycopg.Pipeline [INERROR, pipeline=ON] (host=localhost port=5433 user=arson database=nocartinsights) at 0x77001c229190>: pipeline aborted

DatabaseError: Execution failed on sql 'INSERT INTO orders_items (order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value) VALUES (:order_id, :order_item_id, :product_id, :seller_id, :shipping_limit_date, :price, :freight_value)': (psycopg.errors.ForeignKeyViolation) insert or update on table "orders_items" violates foreign key constraint "orders_items_product_id_fkey"
DETAIL:  Key (product_id)=(ff6caf9340512b8bf6d2a2a6df032cfa) is not present in table "products".
[SQL: INSERT INTO orders_items (order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value) VALUES (%(order_id)s::VARCHAR, %(order_item_id)s::BIGINT, %(product_id)s::VARCHAR, %(seller_id)s::VARCHAR, %(shipping_limit_date)s::TIMESTAMP WITHOUT TIME ZONE, %(price)s, %(freight_value)s)]
[parameters: [{'order_id': '00010242fe8c5a6d1ba2dd792cb16214', 'order_item_id': 1, 'product_id': '4244733e06e7ecb4970a6e2683c13e61', 'seller_id': '48436dade18ac8b2bce089ec2a041202', 'shipping_limit_date': datetime.datetime(2017, 9, 19, 9, 45, 35), 'price': 58.9, 'freight_value': 13.29}, {'order_id': '00018f77f2f0320c557190d7a144bdd3', 'order_item_id': 1, 'product_id': 'e5f2d52b802189ee658865ca93d83a8f', 'seller_id': 'dd7ddc04e1b6c2c614352b383efe2d36', 'shipping_limit_date': datetime.datetime(2017, 5, 3, 11, 5, 13), 'price': 239.9, 'freight_value': 19.93}, {'order_id': '000229ec398224ef6ca0657da4fc703e', 'order_item_id': 1, 'product_id': 'c777355d18b72b67abbeef9df44fd0fd', 'seller_id': '5b51032eddd242adc84c38acab88f23d', 'shipping_limit_date': datetime.datetime(2018, 1, 18, 14, 48, 30), 'price': 199.0, 'freight_value': 17.87}, {'order_id': '00024acbcdf0a6daa1e931b038114c75', 'order_item_id': 1, 'product_id': '7634da152a4610f1595efa32f14722fc', 'seller_id': '9d7a1d34a5052409006425275ba1c2b4', 'shipping_limit_date': datetime.datetime(2018, 8, 15, 10, 10, 18), 'price': 12.99, 'freight_value': 12.79}, {'order_id': '00042b26cf59d7ce69dfabb4e55b4fd9', 'order_item_id': 1, 'product_id': 'ac6c3623068f30de03045865e4e10089', 'seller_id': 'df560393f3a51e74553ab94004ba5c87', 'shipping_limit_date': datetime.datetime(2017, 2, 13, 13, 57, 51), 'price': 199.9, 'freight_value': 18.14}, {'order_id': '00048cc3ae777c65dbb7d2a0634bc1ea', 'order_item_id': 1, 'product_id': 'ef92defde845ab8450f9d70c526ef70f', 'seller_id': '6426d21aca402a131fc0a5d0960a3c90', 'shipping_limit_date': datetime.datetime(2017, 5, 23, 3, 55, 27), 'price': 21.9, 'freight_value': 12.69}, {'order_id': '00054e8431b9d7675808bcb819fb4a32', 'order_item_id': 1, 'product_id': '8d4f2bb7e93e6710a28f34fa83ee7d28', 'seller_id': '7040e82f899a04d1b434b795a43b4617', 'shipping_limit_date': datetime.datetime(2017, 12, 14, 12, 10, 31), 'price': 19.9, 'freight_value': 11.85}, {'order_id': '000576fe39319847cbb9d288c5617fa6', 'order_item_id': 1, 'product_id': '557d850972a7d6f792fd18ae1400d9b6', 'seller_id': '5996cddab893a4652a15592fb58ab8db', 'shipping_limit_date': datetime.datetime(2018, 7, 10, 12, 30, 45), 'price': 810.0, 'freight_value': 70.75}  ... displaying 10 of 112650 total bound parameter sets ...  {'order_id': 'fffe18544ffabc95dfada21779c9644f', 'order_item_id': 1, 'product_id': '9c422a519119dcad7575db5af1ba540e', 'seller_id': '2b3e4a2a3ea8e01938cabda2a3e5cc79', 'shipping_limit_date': datetime.datetime(2017, 8, 21, 0, 4, 32), 'price': 55.99, 'freight_value': 8.72}, {'order_id': 'fffe41c64501cc87c801fd61db3f6244', 'order_item_id': 1, 'product_id': '350688d9dc1e75ff97be326363655e01', 'seller_id': 'f7ccf836d21b2fb1de37564105216cc1', 'shipping_limit_date': datetime.datetime(2018, 6, 12, 17, 10, 13), 'price': 43.0, 'freight_value': 12.79}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)