# Data Cleaning

In [1]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [2]:
p_dir = project_dir()

raw_data_dir =  p_dir.RAW_DATA_DIR

orders = raw_data_dir/'olist_orders_dataset.csv'
products = raw_data_dir/'olist_products_dataset.csv'
sellers = raw_data_dir/'olist_sellers_dataset.csv'
category = raw_data_dir /'product_category_name_translation.csv'

In [3]:
cleaned_data_dir = p_dir.CLEANED_DIR

## Orders table cleaning

In [4]:
orders_df = pd.read_csv(orders)
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
26535,076d3284be23e6c6ed0267f87775b62f,a466a6b7b523a9ad0b85a1872a03c264,delivered,2018-02-07 06:05:06,2018-02-08 08:56:15,2018-02-08 20:21:34,2018-02-21 21:09:18,2018-03-06 00:00:00
50844,7748ff99ce730984ae58e28b2573feb3,e73222883f05cc599adf2c327970e3b1,delivered,2017-03-21 11:59:10,2017-03-21 11:59:10,2017-03-23 08:42:41,2017-04-10 15:33:04,2017-04-12 00:00:00
1541,a4d7c8bca45b56444e3c59ddcca7d7c9,fcdb673d0f8d2b84d3862193f17a08f9,delivered,2017-08-29 12:36:36,2017-08-30 02:05:44,2017-09-04 21:21:52,2017-09-08 21:36:28,2017-09-22 00:00:00
67583,d47de9b5f1b4feb44d50ca860da9cce3,c0a7a9931c9aecec70be96594d6504e3,delivered,2018-02-17 11:12:08,2018-02-17 11:26:56,2018-02-27 21:49:09,2018-03-20 20:41:47,2018-03-22 00:00:00
92927,4e204da6cc8b59dcfdc532fb5a9281f0,2ffdb3851fb34c5c1fdfd9b9116c0103,delivered,2018-06-05 16:30:23,2018-06-05 16:53:32,2018-06-06 12:44:00,2018-06-07 18:07:51,2018-07-03 00:00:00

In [5]:
print(orders_df.info())
print(orders_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [6]:
# fixing the date type columns
orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_deliverey_date']] = orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].astype('datetime64[ns]')

In [7]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
10250,aa6bd33ba1853d846d3085a88ae37083,4f061e67c05a2736e7c07286ff3fa787,delivered,2018-08-10 21:36:37,2018-08-10 21:50:23,2018-08-13 15:18:00,2018-08-17 17:04:32,2018-08-23 00:00:00,2018-08-23
46651,84a5898c018be5c7ee3e45969708ebbe,a280ef36b320f176238aca454824fd91,delivered,2018-06-14 13:39:00,2018-06-15 02:17:29,2018-06-15 17:25:00,2018-06-21 17:18:58,2018-07-16 00:00:00,2018-07-16
94869,f8da7d096b125f74ad5b784140c294c7,f8f3a29c793887b5d14a19247cefc805,delivered,2017-10-16 18:24:03,2017-10-16 18:45:43,2017-10-20 18:33:25,2017-10-30 18:53:47,2017-11-08 00:00:00,2017-11-08
86340,952ae74fec51be4a3dd2b542bd77843d,eba6b4c02a87d8d361314e878cd67fdb,delivered,2017-06-28 10:48:08,2017-06-28 11:05:10,2017-06-28 16:16:22,2017-06-29 11:39:35,2017-07-11 00:00:00,2017-07-11
3738,92ea4e83a1cbd42cfc62e113b8a00797,5c9039026e45902bdd7d7491e04071c6,delivered,2018-07-17 13:22:47,2018-07-17 13:35:23,2018-07-18 15:21:00,2018-07-30 12:18:34,2018-08-06 00:00:00,2018-08-06

In [8]:
## handling the missing values 

orders_df[orders_df['order_delivered_carrier_date'].isna()].sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
55515,0e6b2d0fe443a6d38c0f6447f4eb2262,35bfa7ce75679810efa7d433811c6945,unavailable,2017-11-03 20:44:04,2017-11-07 08:30:54,NaT,NaT,2017-11-28 00:00:00,2017-11-28
40507,fc20b8e282da6f3fbcdd3a3cedecb723,58acc4e2788bf6fc445fddcce9c1db03,unavailable,2017-03-01 10:02:02,2017-03-02 08:10:15,NaT,NaT,2017-03-20 00:00:00,2017-03-20
36884,7114487751b14b1d7f547fefba1eec75,d9701914d7ce67dae929a04783aa18d2,canceled,2017-11-22 19:56:37,2017-11-22 20:26:11,NaT,NaT,2017-12-12 00:00:00,2017-12-12
74753,1800254c5ad71baad5c53866d4ed0ea0,f872eb3035d6adfa491660d3d0f8f86d,unavailable,2017-11-14 11:38:34,2017-11-14 11:50:40,NaT,NaT,2017-12-04 00:00:00,2017-12-04
27167,5f0dfd096a455e93ffb4ee0635b32264,b03efbab821a8ef7b3e6b2a75ec7d74d,canceled,2018-07-29 15:15:39,2018-07-29 15:25:09,NaT,NaT,2018-08-02 00:00:00,2018-08-02
75279,3b4b5ec89dc09c7aedc74199be65fef7,9e6179dbe5933b2f9ed17280257f1c97,unavailable,2017-10-18 11:33:40,2017-10-18 11:50:13,NaT,NaT,2017-11-21 00:00:00,2017-11-21
34574,405d28af4fe06990456c82cdfe457b1a,0a2d230e2761d958999166488ce599fe,invoiced,2017-04-05 09:11:24,2017-04-05 09:22:51,NaT,NaT,2017-05-04 00:00:00,2017-05-04
68758,f05fbff4a434f4d0c1e09000bf45f06f,dc707154393bfd176a45a7bdd7e496a0,unavailable,2017-06-10 12:33:10,2017-06-10 13:02:14,NaT,NaT,2017-07-07 00:00:00,2017-07-07
97982,af264f3527e94e431f0dcd56cd6b406d,8118922685d2e2c0205f060be4f2579c,unavailable,2017-07-12 14:49:11,2017-07-12 15:04:10,NaT,NaT,2017-08-11 00:00:00,2017-08-11
55132,2463e85fc460252cacb332c69099f298,f6132655cb97ab93f1c8ace4528520a1,unavailable,2017-10-18 19:11:27,2017-10-18 19:28:44,NaT,NaT,2017-11-09 00:00:00,2017-11-09

In [9]:
orders_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [10]:
orders_df.duplicated().sum()

np.int64(0)

## Products Dataset Cleaning

In [11]:
products_df = pd.read_csv(products)
products_df.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
5690,a7841f8c0ca7736a81dd679c39d7fd21,moveis_decoracao,50.0,1831.0,3.0,7600.0,65.0,5.0,47.0
29434,5691a536d459e5cb326b7bedce928067,climatizacao,41.0,775.0,4.0,8600.0,29.0,50.0,25.0
8690,355e78eaf102f03855b48498d1b7e996,brinquedos,43.0,545.0,1.0,9700.0,30.0,80.0,40.0
25354,8015f5d7a88ec30688c99aa9486561f7,telefonia,51.0,44.0,1.0,100.0,20.0,20.0,20.0
23280,e708a48b26e6681db248ca125459d365,construcao_ferramentas_construcao,23.0,451.0,1.0,100.0,30.0,30.0,30.0
2573,5b0b1b9c6b42c532349cfa6d0d5bfa58,beleza_saude,53.0,871.0,1.0,1550.0,25.0,23.0,23.0
21840,421730bc1e40e869255cc20542bd2444,esporte_lazer,33.0,150.0,1.0,300.0,16.0,25.0,11.0
22044,245baefabc49c30568e720610780fa9b,utilidades_domesticas,46.0,817.0,1.0,6370.0,45.0,28.0,40.0
26869,7b123554850fa548f45e478a4726ac55,automotivo,55.0,867.0,5.0,2550.0,68.0,9.0,35.0
1714,c04e948c6900ce99ac47d89b3b6d70cd,cool_stuff,33.0,1401.0,2.0,30000.0,70.0,37.0,70.0

In [12]:
products_df.info()
# TO-DO : fix columns name

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [13]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [14]:
products_df.duplicated().sum()

np.int64(0)

In [15]:
products_df['product_category_name'].value_counts().to_string('../arson/product_category.csv') ## question to ask, why there are no NaN values in my arson folder of this query.
products_df[products_df['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [16]:
# dropping missing values. 
products_df = products_df.dropna()

In [17]:
print(products_df.shape)
products_df.isnull().sum()

(32340, 9)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [18]:
products_df = products_df.rename(columns={
    'product_category_name': 'category_name',
    'product_name_lenght' : 'name_length',
    'product_description_lenght' : 'description_length',
    'product_photos_qty' : 'photos_qty',
    'product_weight_g' : 'weight_g',
    'product_length_cm' : 'length_cm',
    'product_height_cm' : 'height_cm',
    'product_width_cm' : 'width_cm'
})
products_df.sample(10)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm
30389,090ab1523d3fe5832c09a55b7195e32b,telefonia,41.0,391.0,2.0,117.0,18.0,6.0,12.0
21023,91c30c59ba5ecdf9df48ab0ea50a6b4e,esporte_lazer,41.0,961.0,1.0,3276.0,24.0,25.0,24.0
29394,9751b280db38705e0225fcbad03d17cc,moveis_decoracao,60.0,646.0,1.0,3200.0,36.0,30.0,19.0
329,c04b8195870068ff5c495f269a0bc993,livros_tecnicos,54.0,1162.0,1.0,1100.0,29.0,3.0,21.0
15298,c55065b87cbfeb89e7714d838d588afd,cama_mesa_banho,50.0,256.0,1.0,2300.0,40.0,7.0,30.0
23423,f75b94ae22e65bec6b67d9652ef8387c,informatica_acessorios,50.0,872.0,1.0,650.0,16.0,29.0,22.0
13125,9ede4fa4d396a0b47c8b5524103436fb,esporte_lazer,48.0,255.0,1.0,450.0,16.0,12.0,12.0
27334,cbf1e8ec6dcc62ec159b265948abfa0b,brinquedos,57.0,520.0,5.0,3400.0,52.0,7.0,56.0
10881,12fd8665371236b5b586ea4e448902c8,casa_conforto,61.0,292.0,1.0,4050.0,45.0,15.0,35.0
14041,687ada1b5c787ece71130a5ec0123567,audio,59.0,214.0,6.0,2300.0,20.0,20.0,32.0

In [25]:
products_df.to_csv(cleaned_data_dir/'cleaned_products.csv')

## Sellers Dataset cleaning

In [20]:
sellers_df = pd.read_csv(sellers)
sellers_df.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
1118,4a82c4af97ffc0fb2dc26bfdc03b1842,35590,lagoa da prata,MG
899,b32be1695eb7ec5f10f72d9610a12527,95012,caxias do sul,RS
2464,478bfe564db21eeb44386606aa30b650,33600,pedro leopoldo,MG
95,cda598c48d7c614bc1cad7d8ff6f0010,15137,mirassol,SP
1246,2156f2671501a81034d7d07f217609d0,4776,sp,SP
2231,05730013efda596306417c3b09302475,88813,criciuma,SC
1484,e9c6969d40e6a3d2d0f90013165c2b98,3448,sao paulo,SP
2724,891071be6ba827b591264c90c2ae8a63,3872,sao paulo,SP
1323,5b8154610ebb21fb90eb587365e673df,12246,sao jose dos campos,SP
42,a81466620e46a6970b22ef40379fdfc9,88730,sao ludgero,SC

In [21]:
sellers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [22]:
sellers_df.duplicated().sum()

np.int64(0)

In [23]:
sellers_df.groupby('seller_city')[['seller_state','seller_zip_code_prefix']].value_counts().to_string('../arson/sellers_state.csv')

In [24]:
# Question to ask: how to handle the invalid values in sellers_city columns