# Data Cleaning

In [4]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [5]:
p_dir = project_dir()

raw_data_dir =  p_dir.RAW_DATA_DIR

orders = raw_data_dir/'olist_orders_dataset.csv'
products = raw_data_dir/'olist_products_dataset.csv'
sellers = raw_data_dir/'olist_sellers_dataset.csv'
category = raw_data_dir /'product_category_name_translation.csv'

In [6]:
cleaned_data_dir = p_dir.CLEANED_DIR

## Orders table cleaning

In [7]:
orders_df = pd.read_csv(orders)
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
23160,3101c208f7e41c66b3929266928afa56,7877cd36cf788987d0e8ec3e5aedfa05,delivered,2017-11-04 20:42:48,2017-11-04 20:55:47,2017-11-07 01:31:47,2017-11-13 15:28:55,2017-11-29 00:00:00
25609,8f872e715d0dc90d10e7315809cdd49a,808dadb433aad1c6a2a45dcf10fb69b2,delivered,2017-08-10 18:04:32,2017-08-10 18:15:20,2017-08-14 14:16:01,2017-08-25 19:37:54,2017-09-01 00:00:00
66364,bb5069a1c4caa1d28fe56f4c647d23cc,f2c48cad58997d0feebf4637a312a767,delivered,2017-12-07 09:22:20,2017-12-08 02:54:34,2017-12-09 16:31:28,2018-01-04 00:58:59,2018-01-23 00:00:00
63151,83c6401c172501d8dbb2cb1c89a51b01,57ea77d77b05b87eb8328d8bbcc4b7ef,delivered,2018-03-20 02:29:16,2018-03-21 02:28:18,2018-03-23 00:45:47,2018-04-03 00:37:51,2018-04-11 00:00:00
33019,345de0cb4a0a058abaa652096fd1f89e,faae7c482c489250578077e52576b3e9,delivered,2017-06-29 16:24:53,2017-06-29 16:35:45,2017-07-04 14:03:00,2017-07-13 18:59:56,2017-07-25 00:00:00

In [8]:
print(orders_df.info())
print(orders_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [9]:
# fixing the date type columns
orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_deliverey_date']] = orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].astype('datetime64[ns]')

In [10]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
62805,cb31d6a654b3b6be3168cdb05fee80ee,7d5599e9950b5055d91871998db3ff7c,delivered,2018-01-25 14:01:47,2018-01-26 03:17:28,2018-01-29 18:39:01,2018-02-22 10:18:56,2018-03-05 00:00:00,2018-03-05
43968,761d2a6c3fc081b13c3cbfa01c4a8c37,eeb1a37e2e928ef2bacdb4b6382badc6,delivered,2017-08-17 00:19:21,2017-08-18 00:30:15,2017-09-06 21:35:05,2017-09-14 14:58:50,2017-09-11 00:00:00,2017-09-11
30163,1b46c5cd349b4c1e7bda383bb8d64731,9a3f52e1bec201f8966f6d0a8faddbb4,delivered,2017-07-17 21:48:20,2017-07-18 21:55:10,2017-07-19 19:05:31,2017-07-24 21:32:44,2017-08-09 00:00:00,2017-08-09
20821,69a3d3d4af1b74db85965b00394b5d21,d701d4f8da8a0d17c1fbf6e134d07c4f,delivered,2017-11-26 20:11:16,2017-11-26 20:19:27,2017-11-28 17:32:32,2017-12-05 15:33:39,2017-12-20 00:00:00,2017-12-20
55320,f2c9428d2c7720cb4e9f2a9634673ce6,80825fac1b288cd8a58c4ae40c66a821,delivered,2017-10-22 10:17:43,2017-10-22 10:28:11,2017-10-23 21:32:06,2017-12-27 21:06:58,2017-11-10 00:00:00,2017-11-10

In [11]:
## handling the missing values 

orders_df[orders_df['order_delivered_carrier_date'].isna()].sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
55654,5de59551c282b892ae9ff238fd557145,7543dc2c9f203502439305c8b2ea63bc,invoiced,2017-01-16 16:24:13,2017-01-16 17:31:50,NaT,NaT,2017-02-24 00:00:00,2017-02-24
87231,79fe48b364804e62431c8f465e16f76e,857fe5831ff74761c8b171203310c83c,canceled,2017-11-09 06:13:41,2017-11-10 06:10:31,NaT,NaT,2017-11-29 00:00:00,2017-11-29
89083,bfd31c6f76ff82a41e7beb05565aec4d,6c65055adfbc0007dbb4c5a22ea5ba8c,canceled,2016-10-04 14:51:15,2016-10-06 15:56:40,NaT,NaT,2016-12-14 00:00:00,2016-12-14
35310,82ba09cde004c6bcefd36545670ac5de,61523d11d253c053d2567669b8e761d6,invoiced,2017-12-05 21:34:58,2017-12-05 21:58:41,NaT,NaT,2017-12-29 00:00:00,2017-12-29
70615,b81dc96814c73196e795524a469a2c35,ed3f4ba1e8981bd3773207b41a9de82b,invoiced,2018-08-07 19:13:51,2018-08-07 19:25:15,NaT,NaT,2018-08-21 00:00:00,2018-08-21
14079,21d4d409001930a8266042afbc040039,85767455bb630bfef897cb4e78647be6,invoiced,2017-11-08 12:38:38,2017-11-09 04:31:08,NaT,NaT,2017-12-05 00:00:00,2017-12-05
99051,e58b8168894c93cf61d36c90775acd85,65a227fbf7d798cdeadee8c0bea74993,unavailable,2017-02-26 16:13:36,2017-02-26 16:25:15,NaT,NaT,2017-03-22 00:00:00,2017-03-22
25023,1aaa4f61529fb2b392016a694b437885,7f6c1d60597d2edb5adf63fef310e932,processing,2017-12-26 15:47:25,2017-12-26 15:56:20,NaT,NaT,2018-01-26 00:00:00,2018-01-26
30904,53a71627049b3cd04fe655e979d8b4a6,74b82d49b3b81780a41bcfe099abeb86,processing,2018-04-20 11:20:41,2018-04-20 11:35:16,NaT,NaT,2018-05-17 00:00:00,2018-05-17
72190,3757dc827b45811e32f858867877df67,442c2a88842315cb04a3d46658371689,processing,2017-08-21 10:59:48,2017-08-23 02:46:19,NaT,NaT,2017-09-14 00:00:00,2017-09-14

In [12]:
orders_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [13]:
orders_df.duplicated().sum()

np.int64(0)

#### handling the missing dates

In [14]:
orders_df[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].isna().sum()

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [15]:
orders_df[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date','order_status']].groupby('order_status').value_counts().to_string('../arson/order_status_date.csv')

In [16]:
orders_df.groupby('order_status')[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date']].apply(
    lambda x: x.isnull().sum()
)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609


## Products Dataset Cleaning

In [17]:
products_df = pd.read_csv(products)
products_df.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
31550,ac477a098cb23c128ec2915a4f3c4625,beleza_saude,38.0,1686.0,2.0,717.0,19.0,17.0,14.0
6336,f56596f8f7191441f17b1a1fbfe37a75,brinquedos,46.0,195.0,2.0,575.0,23.0,17.0,20.0
2312,aa95bee0592e05d2ef533b8e5b7236b3,ferramentas_jardim,53.0,313.0,1.0,500.0,36.0,3.0,11.0
19733,8b8191f9283cd3c98fa9b37a0b0f99ef,perfumaria,45.0,854.0,1.0,400.0,23.0,10.0,20.0
14972,68753ceccf509d2890f329f8d55fce79,eletronicos,59.0,700.0,4.0,420.0,16.0,8.0,12.0
8425,7c3dd2ee1b4512bc2c741154fc0d2ad3,eletrodomesticos,39.0,99.0,1.0,147.0,22.0,15.0,22.0
32375,d06d1c1f54c64e227690d22eb48855b2,esporte_lazer,39.0,2269.0,3.0,300.0,20.0,17.0,22.0
26738,6b4738836ca838a18b9d08d35bf6b2b6,beleza_saude,60.0,1137.0,1.0,600.0,16.0,2.0,11.0
22079,68821aa251c8715f0c4199f413511411,esporte_lazer,20.0,582.0,1.0,11150.0,28.0,4.0,28.0
10180,5e72175cdfc45b8211c357f26d5c3b01,cama_mesa_banho,53.0,555.0,2.0,533.0,54.0,6.0,37.0

In [18]:
products_df.info()
# TO-DO : fix columns name

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [19]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [20]:
products_df.duplicated().sum()

np.int64(0)

In [21]:
products_df['product_category_name'].value_counts().to_string('../arson/product_category.csv') ## question to ask, why there are no NaN values in my arson folder of this query.
products_df[products_df['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [22]:
# dropping missing values. 
products_df = products_df.dropna()

In [23]:
print(products_df.shape)
products_df.isnull().sum()

(32340, 9)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [24]:
products_df = products_df.rename(columns={
    'product_category_name': 'category_name',
    'product_name_lenght' : 'name_length',
    'product_description_lenght' : 'description_length',
    'product_photos_qty' : 'photos_qty',
    'product_weight_g' : 'weight_g',
    'product_length_cm' : 'length_cm',
    'product_height_cm' : 'height_cm',
    'product_width_cm' : 'width_cm'
})
products_df.sample(10)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm
13079,33d572fab2a1a7c217d8831ade7d9357,pet_shop,37.0,964.0,3.0,25950.0,60.0,36.0,42.0
17260,d7d1cdd61c66570cac78c88a0cae784b,telefonia,46.0,394.0,3.0,200.0,19.0,3.0,11.0
23578,e93009b6d983b9f87a984b7fc9e67240,bebes,58.0,489.0,2.0,300.0,25.0,20.0,20.0
19863,32267de030005084d4b6af64f22143b8,moveis_decoracao,51.0,567.0,1.0,1150.0,30.0,10.0,30.0
10333,7104eafd29c0b00fe99250034af0d978,consoles_games,48.0,2532.0,3.0,998.0,27.0,13.0,24.0
18428,60d49071f68566b7254c39a7d4ea5c1c,eletrodomesticos,56.0,385.0,2.0,100.0,19.0,8.0,13.0
22478,60f98d8f55a602509885faf42c0095a2,perfumaria,57.0,770.0,1.0,343.0,18.0,14.0,15.0
27291,ba29a4c469271c108790a9dcf0344716,telefonia,45.0,402.0,12.0,90.0,19.0,3.0,11.0
20818,cad39e71c0fe2f6ce875040d4ac43a4b,relogios_presentes,34.0,580.0,1.0,642.0,20.0,13.0,16.0
31591,c837ca3eaf5506275072300511cb7b12,beleza_saude,54.0,2564.0,1.0,300.0,16.0,6.0,11.0

In [25]:
products_df.to_csv(cleaned_data_dir/'cleaned_products.csv')

## Sellers Dataset cleaning

In [26]:
sellers_df = pd.read_csv(sellers)
sellers_df.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
1993,d32e3909cfb714fb2a6cb092c85b9c5f,13215,jundiai,SP
1080,5882820ef11c4c068eea0677a7a879b4,95082,caxias do sul,RS
648,252e76235acb79183cfca6e34f13337d,13090,campinas,SP
404,ac51cac5e20d69ff485a54746488ef48,14096,ribeirao preto,SP
2790,bce6a5ecf98e99fd2a8868b15c51f04b,7180,guarulhos,SP
68,7e93a43ef30c4f03f38b393420bc753a,6429,barueri,SP
72,a13aaf2d2886ab9fb30fb9a920160b8f,89207,joinville,SC
1724,e732329483fd5f27367dd997b47f598a,89030,blumenau,SC
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
944,a5bff0f43eb51f0cad7c37fac7244c8a,4827,sao paulo,SP

In [27]:
sellers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [28]:
sellers_df.duplicated().sum()

np.int64(0)

In [29]:
sellers_df.groupby('seller_city')[['seller_state','seller_zip_code_prefix']].value_counts().to_string('../arson/sellers_state.csv')

In [30]:
# Question to ask: how to handle the invalid values in sellers_city columns

In [31]:
orders_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_estimated_deliverey_date'],
      dtype='str')

In [32]:
orders_df.groupby('order_status')[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date']].apply(
    lambda x : x.isnull().sum()
)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [35]:
orders_df.to_csv(cleaned_data_dir/'cleaned_orders.csv')

In [37]:
sellers_df.to_csv(cleaned_data_dir/'cleaned_sellers.csv')