# Data Cleaning

In [72]:
import pandas as pd
import numpy as np
from configs.settings import project_dir

In [73]:
p_dir = project_dir()

raw_data_dir =  p_dir.RAW_DATA_DIR

orders = raw_data_dir/'olist_orders_dataset.csv'
products = raw_data_dir/'olist_products_dataset.csv'
sellers = raw_data_dir/'olist_sellers_dataset.csv'
category = raw_data_dir /'product_category_name_translation.csv'

## Orders table cleaning

In [74]:
orders_df = pd.read_csv(orders)
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
11682,065ac4b340bafd4f6bee041c63e10aef,9c29746c15ba972bc51e23fcdc498216,delivered,2017-06-02 12:37:27,2017-06-02 13:10:55,2017-06-03 09:38:18,2017-06-13 17:29:55,2017-06-27 00:00:00
41975,df81dcb40098fb783a6525fa2f868bc9,749a270cfd211b20bea5c61663a99542,delivered,2018-03-24 16:43:58,2018-03-24 16:56:07,2018-04-16 13:54:53,2018-06-20 22:32:03,2018-05-04 00:00:00
51183,5d008946b4867d5a4cbfb2b94d9e1496,ac4d8a51c24011ff9d9647013254d513,delivered,2017-03-03 09:10:02,2017-03-03 09:22:00,2017-03-09 06:04:39,2017-03-10 09:45:32,2017-03-22 00:00:00
64692,4c5277b8c416e92df5b5b5b3882b4d58,7bba4420a869ab8dba1c7096358c1d66,delivered,2017-05-10 19:59:24,2017-05-10 20:05:14,2017-05-11 10:09:25,2017-05-16 16:29:11,2017-05-30 00:00:00
73544,8821146ecf8a1eb441aa052b371f1814,6d41885118d1c89e00b8a67eb3e74653,delivered,2018-08-11 08:47:48,2018-08-11 09:04:28,2018-08-13 16:21:00,2018-08-15 16:26:52,2018-08-16 00:00:00

In [75]:
print(orders_df.info())
print(orders_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [76]:
# fixing the date type columns
orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_deliverey_date']] = orders_df[['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']].astype('datetime64[ns]')

In [77]:
orders_df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
26713,d77c01a7f1b1ea093949dbc6fe3cc2fa,2e4bda9c3b716e596451491497474dd3,delivered,2018-04-25 17:25:13,2018-04-25 17:55:27,2018-04-30 06:21:00,2018-05-05 11:02:28,2018-05-28 00:00:00,2018-05-28
5161,5ee7b62e53d3ff1201ab0f826ce413db,72adcf6a1e2e058550157b9ee9e202d8,delivered,2017-05-24 15:41:46,2017-05-24 15:55:10,2017-05-30 08:38:18,2017-06-02 16:22:08,2017-06-20 00:00:00,2017-06-20
86055,e7666f6bc0e98144ecc793ddbbdccc08,b0902450a721bbf06e520c99318a63a0,delivered,2018-01-23 14:58:44,2018-01-23 15:12:54,2018-01-31 19:07:57,2018-02-01 18:54:33,2018-02-07 00:00:00,2018-02-07
21158,d7511947889e0d0717a337554a6216ac,2d286468f438650339946ef48c13c971,delivered,2018-05-14 22:22:00,2018-05-14 22:37:50,2018-05-16 06:34:00,2018-05-21 20:18:48,2018-05-30 00:00:00,2018-05-30
87853,cf34fe44babb9fd001a001acfa43cabf,fe082a45e6e64db9443e39ef7e3d415a,delivered,2017-11-06 18:36:52,2017-11-07 04:32:03,2017-11-10 22:07:45,2017-11-18 09:21:44,2017-11-24 00:00:00,2017-11-24

In [78]:
## handling the missing values 

orders_df[orders_df['order_delivered_carrier_date'].isna()].sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_estimated_deliverey_date
40360,e40d0c72305e1f0be6925df1e4378221,09cb79df62a7ca61507fca903adfe410,unavailable,2017-11-03 20:21:30,2017-11-03 20:35:23,NaT,NaT,2017-12-01 00:00:00,2017-12-01
79566,e137acc00a73478b179ca50de0176bbb,d36226a75bd645b98eb282c9ac967eb2,invoiced,2018-07-18 15:28:39,2018-07-18 15:42:30,NaT,NaT,2018-08-13 00:00:00,2018-08-13
28651,83fc33b62b8c7c39e2258d081955143d,c6eb22e4e7b7e5b871c06250c3296ef9,processing,2018-05-15 20:00:48,2018-05-17 02:55:42,NaT,NaT,2018-05-30 00:00:00,2018-05-30
39534,5057598da256a7629c0f6f21877215ba,16c2b0a5ce42533979d3f8150e1298c5,invoiced,2018-07-11 09:23:23,2018-07-11 09:30:30,NaT,NaT,2018-08-08 00:00:00,2018-08-08
19035,5754d3172f19f363edbaf03691b9f989,d56b30f9f6b0167e61eb297deabfad78,canceled,2018-02-09 11:23:59,2018-02-09 11:35:31,NaT,NaT,2018-03-07 00:00:00,2018-03-07
38928,8b564962527dd053cfc85c8fc98ad1df,7a9f83795de1c16c6be36870eccd9b10,unavailable,2017-10-09 16:38:21,2017-10-09 16:56:30,NaT,NaT,2017-11-08 00:00:00,2017-11-08
39165,ccb48770165d34335e1d156d6d2c6ec7,4b51c20a256e426ffa5fdf3471d20cfe,unavailable,2018-02-15 12:39:44,2018-02-15 12:50:26,NaT,NaT,2018-03-13 00:00:00,2018-03-13
49879,3a0fbe8fbdae776394cd93385366a4fd,240316d3cc8d0622aa5a02aa0de18115,unavailable,2017-12-12 14:23:58,2017-12-12 15:31:22,NaT,NaT,2018-01-08 00:00:00,2018-01-08
15814,6da45c88a41888408e61bfe388d93f01,ea94754b4cd71085c914bf60e5a2dd56,invoiced,2017-10-03 01:38:04,2017-10-04 02:44:06,NaT,NaT,2017-10-24 00:00:00,2017-10-24
14638,2c44ef48e157c9a43e9998da9a3248bd,1b38122bd6186b187d3af336471189e8,unavailable,2017-07-17 15:43:37,2017-07-18 06:35:14,NaT,NaT,2017-08-18 00:00:00,2017-08-18

In [79]:
orders_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [80]:
orders_df.duplicated().sum()

np.int64(0)

## Products Dataset Cleaning

In [81]:
products_df = pd.read_csv(products)
products_df.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
10394,4ede085df4efad73e78ee270b669f7aa,beleza_saude,57.0,656.0,4.0,605.0,34.0,13.0,11.0
23775,ecc224ec2ca908e1fdacf9aaad00fbe1,papelaria,56.0,456.0,3.0,11950.0,18.0,46.0,33.0
10875,652b2c3cfb3ca763c54795335a22f1ad,pet_shop,53.0,468.0,1.0,200.0,16.0,8.0,15.0
28871,5b45b90d432972e54f815d543084e6ae,brinquedos,58.0,423.0,3.0,400.0,18.0,14.0,12.0
5576,72a26085dd4fbd27f7206188081008d9,utilidades_domesticas,47.0,587.0,3.0,1000.0,28.0,12.0,21.0
30570,b48946c4c9a1d7c81916522d00d6722f,fashion_bolsas_e_acessorios,58.0,392.0,4.0,50.0,16.0,6.0,20.0
76,278b3c6462e86b4556b99989513ddf73,eletroportateis,58.0,587.0,3.0,350.0,20.0,20.0,20.0
27505,02ca198b1084a6d8ed9e152d84243bfb,bebes,58.0,544.0,3.0,2650.0,16.0,24.0,24.0
8592,9d32095f76b97762307e86cfc18dd7a0,cama_mesa_banho,38.0,213.0,2.0,400.0,25.0,9.0,19.0
7188,b29c1749f99da888ea322a01420d5220,tablets_impressao_imagem,60.0,2532.0,5.0,1100.0,30.0,5.0,22.0

In [82]:
products_df.info()
# TO-DO : fix columns name

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [83]:
products_df.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [84]:
products_df.duplicated().sum()

np.int64(0)

In [85]:
products_df['product_category_name'].value_counts().to_string('../arson/product_category.csv') ## question to ask, why there are no NaN values in my arson folder of this query.
products_df[products_df['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [ ]:
# dropping missing values. 
products_df = products_df.dropna()

In [93]:
print(products_df.shape)
products_df.isnull().sum()

(32340, 9)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [97]:
products_df = products_df.rename(columns={
    'product_category_name': 'category_name',
    'product_name_lenght' : 'name_length',
    'product_description_lenght' : 'description_length',
    'product_photos_qty' : 'photos_qty',
    'product_weight_g' : 'weight_g',
    'product_length_cm' : 'length_cm',
    'product_height_cm' : 'height_cm',
    'product_width_cm' : 'width_cm'
})
products_df.sample(10)

,product_id,category_name,name_length,description_length,photos_qty,weight_g,length_cm,height_cm,width_cm
22380,89197eee3abe531055b90c8ab1df05cc,moveis_decoracao,60.0,1977.0,4.0,2800.0,69.0,11.0,11.0
28846,ef7bac3fcd96b1f97400cb9cf17902d8,brinquedos,53.0,1329.0,7.0,4900.0,23.0,16.0,31.0
25573,cc3f2c3c98c34475aac4da902b2f7eee,informatica_acessorios,52.0,181.0,1.0,100.0,40.0,2.0,24.0
19247,0dc3bdb1240958ec9be2c91cba5bcc57,utilidades_domesticas,47.0,232.0,1.0,250.0,20.0,9.0,12.0
19734,d3a386ad58b99f0ddcc216ed9efb03c3,cama_mesa_banho,42.0,702.0,1.0,840.0,22.0,15.0,22.0
31420,dce3d94fd2f5d6d78c586d93faa33646,malas_acessorios,52.0,560.0,7.0,800.0,30.0,15.0,15.0
25082,06ecc3d4006ad6eb293a1b93ec3c7183,moveis_decoracao,59.0,903.0,1.0,750.0,22.0,22.0,11.0
11146,8f5501bc2a52a32cb42e220c855cd589,pet_shop,58.0,2357.0,6.0,2350.0,42.0,22.0,32.0
18416,af2808733a159ce5dfb2db7ec510f8d4,utilidades_domesticas,54.0,641.0,1.0,1425.0,27.0,19.0,17.0
3212,de80c37c338574091896b7fdc81dc376,beleza_saude,49.0,1045.0,1.0,333.0,17.0,17.0,15.0

## Sellers Dataset cleaning

In [100]:
sellers_df = pd.read_csv(sellers)
sellers_df.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
853,d7485b33791774c36108f8c69602d48d,81020,curitiba,PR
980,f3862c2188522d89860c38a3ea8b550d,14092,ribeirao preto,SP
1883,4d8809767a5bafe22909c77951fb6b41,6803,embu das artes,SP
685,c03121937e54a93fcc1825c3098bbb6e,82800,curitiba,PR
708,9b76ad3d04236f76bc71c59470305e13,18550,boituva,SP
491,8ff1a9df749e454105c55cda13e79143,17509,marilia,SP
2246,53b0300ca793f9834cd69c0678d35ee8,13339,indaiatuba,SP
1568,94144541854e298c2d976cb893b81343,94451,viamao,RS
2916,80ceebb4ee9b31afb6c6a916a574a1e2,86026,londrina,PR
2302,f0ec78809fe0bc3edb11c9fe5b97b059,4291,sao paulo,SP

In [101]:
sellers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [102]:
sellers_df.duplicated().sum()

np.int64(0)

In [107]:
sellers_df.groupby('seller_city')[['seller_state','seller_zip_code_prefix']].value_counts().to_string('../arson/sellers_state.csv')

In [108]:
# Question to ask: how to handle the invalid values in sellers_city columns