## Anova Test

### Do product categories have significantly different average order values?

In [2]:
import pandas as pd
from configs.settings import project_dir

In [3]:
p_dir = project_dir()
feature_dir = p_dir.FEATURE_ENGINEERED
cleaned_dir = p_dir.CLEANED_DIR

In [4]:
foi = feature_dir/'featured_order_items.csv'
fo = feature_dir/'featured_orders.csv'
fp = feature_dir/'featured_products.csv'

In [5]:
foi_df = pd.read_csv(foi,index_col=0)
fo_df = pd.read_csv(fo)
fp_df = pd.read_csv(fp)

In [6]:
foi_df.sample()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count
83361,bd5a6e9434ebae71399bef6eb45d85eb,1,a98a8d36f2c2f97f7d7c4c3222f2251c,c3867b4666c7d76867627c2f7fb22e21,2017-10-26 10:14:43,269.9,14.91,284.81,42197.18,259

In [7]:
fp_df.sample()

,product_id,category_name,name_length,description_length,photos_qty,weight_g,category_name_eng,volume
21625,3880d25d502b15b1de6fddc42ad1d67a,esporte_lazer,48.0,562.0,5.0,9850.0,sports_leisure,183750.0

In [8]:
items_products = pd.merge(foi_df,fp_df,on='product_id',how='inner')

In [9]:
items_products.sample(4)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count,category_name,name_length,description_length,photos_qty,weight_g,category_name_eng,volume
70905,a4101dff2487b4a3d89330b9fe480475,1,c1cf8f51eac90b1ff478250b3d35c37b,bc47d5d1490df2b36add65d733eafaba,2018-06-21 12:32:39,35.0,37.16,72.16,1419.91,25,esporte_lazer,57.0,326.0,2.0,280.0,sports_leisure,5746.0
81120,baf664f0589b605f58b9e6630f0f267a,1,ffaf0af7eebb57c7f262b51ebb05dfd6,376d67b61dce0c990155286e7ae486a4,2018-03-07 15:55:35,94.0,17.91,111.91,111.91,1,beleza_saude,47.0,808.0,1.0,1255.0,health_beauty,4896.0
88017,cac00f6d5c47ea72c4a8f62a307edcda,1,cb9a231b86e78edf9802645824e0b2c1,8ca1551acf9832a4cf467bbbac15851f,2018-04-04 22:30:24,189.9,19.26,209.16,2442.94,12,moveis_decoracao,51.0,333.0,4.0,900.0,furniture_decor,18000.0
84182,c1f534b2a0002528a5e5e5001f6be004,1,98a940d42d3ac029e40441023676ddfe,93dc87703c046b603023e75222018b45,2018-02-02 18:55:21,209.0,45.31,254.31,9206.29,36,esporte_lazer,48.0,1059.0,5.0,483.0,sports_leisure,5796.0

In [10]:
featured_df = pd.merge(items_products,fo_df,on='order_id',how='inner')

In [11]:
featured_df.sample(4)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount,seller_revenue,seller_order_count,...,delivery_days,delivery_delay_days,is_delayed,customer_unique_id,customer_order_count,is_repeat_customer,order_value,order_count,total_spending_by_cust,avg_order_value_count
90775,d0ee2ae87e093d006aed295d79e325f4,2,fa23bf270fb9880690b07d09b9f9ff20,1b8356dabde1d35e17cef975c3f82730,2017-07-11 22:50:07,59.99,16.18,76.17,4413.61,61,...,6.0,-19.0,0.0,378c702fe06f37937a5fb0253f8493d0,1,0,152.34,2.0,152.34,152.34
21533,31ea9af161fd3c77c3c621aa178bcb34,1,1c21c1ed398eae61184065889ca3d4b0,a3e9a2c700480d9bb01fba070ba80a0e,2018-02-08 03:10:35,69.00,17.73,86.73,16323.89,144,...,13.0,-17.0,0.0,83b718d277e811cc84d2d60c375a4573,1,0,86.73,1.0,86.73,86.73
100592,e794b6f8bc2c405d7a2038f44b32a5d9,1,9ad75bd7267e5c724cb42c71ac56ca72,8160255418d5aaa7dbdc9f4c64ebda44,2018-03-21 12:49:09,105.90,23.32,129.22,54871.50,431,...,NaN,NaN,NaN,5ff268d5e801827053ce25fb7a055fbb,1,0,129.22,1.0,129.22,129.22
86874,c8114f17241723311fd349c747e151b0,3,d0fac709247e97e9b44a5351891ef9f3,7178f9f4dd81dcef02f62acdf8151e01,2017-07-31 06:15:32,44.90,26.89,71.79,41478.92,216,...,8.0,-33.0,0.0,a5ab01d672d5b6076a01da21446543f2,1,0,215.37,3.0,215.37,215.37

In [12]:
from configs.database import engine

featured_df.to_sql('featured_df',engine,if_exists='replace',index=False)

-1